### ISSUE TITLE
Avoid running on Python 3.6 or ensure compatibility with it

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/drakvuf-sandbox#102]
related #100

sometimes Ubuntu 18.04 has Python 3.6 as default interpreter but we don't really support such situation

**Comment by icedevml** [comment]
Steps to reproduce:

1. Install Ubuntu 18.04 Bionic
2. `apt-get remove -y python3.7 && apt-get install -y python3.6`
3. Install drakcore/drakrun

venv is deployed to `/opt/venvs/drakcore/lib/python3.6` and Python 3.6 is used to run drakcore/drakrun

**Comment by icedevml** [comment]
@chivay

**Comment by icedevml** [comment]
Btw. for Ubuntu 18.04 we do package it with python3.6 by default o_O

but the package ships `/opt/venvs/drakcore/bin/python` which is a symlink to the default Python version in the system

```
lrwxrwxrwx 1 root root   16 Apr 23 03:00 python -> /usr/bin/python3
lrwxrwxrwx 1 root root    6 Apr 23 03:00 python3 -> python
lrwxrwxrwx 1 root root    6 Apr 23 03:00 python3.6 -> python
```

so we are not pinning to the exact interpreter version even though we do require python3.7 package in the DEBIAN/control

**Comment by BonusPlay** [comment]
Rel #64

**Comment by icedevml** [comment]
#65 would help but we need to choose proper interpreter (`python3.8` where available, `python3.7` otherwise) for each distro
