### ISSUE TITLE
Set up Wiki/documentation to allow for understanding of internal workings

### ISSUE THREAD

**Issue by alloygoh** [CERT-Polska/drakvuf-sandbox#103]
A clear and well documented wiki will allow for potential contributors to better understand the internals of the sandbox, allowing for better quality contributions and improvements to the sandbox's design, implementation and plugins. 
This would attract more contributors to the project, accelerating Drakvuf Sandbox's performance.

**Comment by icedevml** [comment]
Sure, we are working on it.

**Comment by BonusPlay** [comment]
(missclick)

**Comment by icedevml** [comment]
Side note: We could consider giving "good first issue" for good first issues. I gave the tag for the actual first issue as it helped us to understand some bug.

**Comment by icedevml** [comment]
:thinking: Hm ok, its different - as far as I understand the feature is for tagging the issues that would be good to be taken by new contributors, not for tagging the good issues in general.

**Comment by BonusPlay** [comment]
That's exactly the trap I fell into

**Comment by chivay** [comment]
Since the docs are set up and some foundations have been created I believe we can close this
