### ISSUE TITLE
ipconfig takes too long

### ISSUE THREAD

**Issue by BonusPlay** [CERT-Polska/drakvuf-sandbox#141]
**Describe the bug**
Without setup internet connection ipconfig command on guest takes too long to execute (4 minutes). We should limit this to ~1 minute.

**Comment by icedevml** [comment]
Is there any timeout parameter in ipconfig or some command like `timeout` in Linux?

**Comment by BonusPlay** [comment]
No, but we could run another cmd with ipconfig, perform a `timeout` (which is sleep on linux) and then `taskkill` the cmd if it exists.

**Comment by icedevml** [comment]
Yup and its super easy to skip it in such case. But afaik we always have internal networking even with `net_enable = 0`, how do you have the situation in which there is no net and no DHCP? Manually edited template?

**Comment by chivay** [comment]
We only require ipconfig call to obtain IP address from DHCP.
When net_enable = 1, and DHCP server is running, the command should finish quickly.
Otherwise there's no one to respond and ipconfig runs for 4 minutes, so we can just skip it when writing `run.bat` file.

:thinking:
