### ISSUE TITLE
Implement convenience command to inject ISO during draksetup

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/drakvuf-sandbox#171]
Allow to mount some ISO (e.g. MS Office installer) during installation process with `draksetup`.

E.g. `draksetup mount /opt/office.iso`.

**Comment by BonusPlay** [comment]
Relevant command `xl qemu-monitor-command "vm-0" "change ide-5632 /path/to/file.iso"`

**Comment by kscieslinski** [comment]
#233
