### ISSUE TITLE
Blank analysis page when procDOT output is malformed

### ISSUE THREAD

**Issue by ninewayhandshake** [CERT-Polska/drakvuf-sandbox#176]
**Describe the bug**

If procmon2dot produces a malformed dotfile the analysis page will fail and just display a blank page. 

The specific case I have encountered pretty frequently is a bug in procDOT where it produces malformed dotfiles when paths contain "%s" so for example something like "%systemroot%" in registry keys.

https://twitter.com/ProcDOT/status/1131437170823241729

Example of malformed dot file that makes the analysis page fail.
[graph.zip](https://github.com/CERT-Polska/drakvuf-sandbox/files/4957248/graph.zip)

The root cause is a bug in procDOT but this should probably be handled more gracefully by the front end.

**Comment by BonusPlay** [comment]
Thank you for this very detailed bug report.
