### ISSUE TITLE
Install all of the Microsoft Visual C++ redistributable packages on postinstall stage

### ISSUE THREAD

**Issue by rakovskij-stanislav** [CERT-Polska/drakvuf-sandbox#191]
In order to take all chances for malware to be run, I suggest to install all of the MS VS packages automatically)

Right not what I do to achieve that:
1. Prepare bridge drak0 like bridge drak1 just copypasting the command flow from `drakrun/main.py`)
2. Download firefox, 
3. Download and install max of the libraries using the url - http://dlltop.ru/soft/46-microsoft-visual-c

What I suggest:
a. Collect all the binaries and attach it as an ISO image like you do it with malware injection to allow users to install them by themselves
b. Or install it automatically during the postinstall stage

**Comment by BonusPlay** [comment]
We're not sure if drakvuf-sandbox should do stuff like "automatically install programs on base snapshot". Some users may want to avoid doing that. I could see "install other programs" batch script added to `postinstall`.
related #170 #171 cc @icedevml @chivay

**Comment by icedevml** [comment]
I bet this should be somehow done by the user, `postinstall` shouldn't install any programs on its own, tho.

There are two related tickets:
* https://github.com/CERT-Polska/drakvuf-sandbox/issues/170 - networking support during the setup phase, so you would be able to download (whatever you want) from the internet
* https://github.com/CERT-Polska/drakvuf-sandbox/issues/171 - inject ISO CD-ROM into the VM during setup phase, so you can have your own ISO disk with all necessary programs / batch script which would setup them

**Comment by icedevml** [comment]
It is possible to mount arbitrary ISO on the postinstall stage, so the user is able to install MSVC++ and any other external software before executing `draksetup postinstall`. This is already described in the "getting started" section. Closing as resolved.
