### ISSUE TITLE
libxl: error: libxl_create.c:671 | libxl_create.c:1233 | [ERROR] Failed to launch VM vm-0

### ISSUE THREAD

**Issue by filipi86** [CERT-Polska/drakvuf-sandbox#220]
Hi Everyone
I'm trying to use the drakvuf sandbox and I'v received the same error in my installations..

I tried:
Ubuntu 18.04 
Debian 10..

but appears the same error in both of than.

Installation based on based packages ( .deb like recommendation here in github) 

Error:
```
[2020-08-26 10:02:09,892][INFO] Ensuring that drakrun@* services are stopped...
[2020-08-26 10:02:09,905][INFO] Performing installation...
[2020-08-26 10:02:26,070][INFO] Checking xen-detect...
Running in PV context on Xen V4.14.
[2020-08-26 10:02:26,082][INFO] Testing if xl tool is sane...
[2020-08-26 10:02:26,145][INFO] Generated VM configuration for vm-0
Parsing config from /etc/drakrun/configs/vm-0.cfg
libxl: error: libxl_create.c:671:libxl__domain_make: domain creation fail: Invalid argument
libxl: error: libxl_create.c:1233:initiate_domain_create: cannot make domain: -3
[2020-08-26 10:02:26,246][ERROR] Failed to launch VM vm-0
Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 163, in install
    subprocess.run('xl create {}'.format(shlex.quote(cfg_path)), shell=True, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'xl create /etc/drakrun/configs/vm-0.cfg' returned non-zero exit status 3.
```
![drakvuf](https://user-images.githubusercontent.com/31785433/91330433-cccc9f80-e79f-11ea-8e95-90098ecc6f4b.png)

Do you have any idea or suggestion?

Best Regards,
Filipi Pires

**Comment by chivay** [comment]
Hi thanks for the report.
Could you attach the contents of `/etc/drakrun/configs/vm-0.cfg` ?

**Comment by filipi86** [comment]
> /etc/drakrun/configs/vm-0.cfg

I tried two ways, but still this error happen

thor@threat-hunting:/opt$ cat /etc/drakrun/configs/vm-0.cfg
arch = 'x86_64'
name = "vm-0"
maxmem = 3048
memory = 3048
vcpus = 2
maxvcpus = 2
builder = "hvm"
boot = "cd,menu=on,splash=/usr/share/drakrun/splash.jpg,splash-time=2000"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "restart"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0:0,websocket=6400"
vncpasswd="Xlqu3GZreIFXgDowxFRs"
usb = 1
usbdevice = "tablet"
altp2m = 2
shadow_memory = 16
audio=1
soundhw='hda'
cpuid="host,htt=0"
vga="stdvga"
vif = [ 'type=ioemu,model=e1000,bridge=drak0' ]
disk = [ "tap:qcow2:/var/lib/drakrun/volumes/vm-0.img,xvda,w", "file:/opt/win7.iso,hdc:cdrom,r" ]
================================================================================

thor@threat-hunting:/opt$ cat /etc/drakrun/configs/vm-0.cfg
arch = 'x86_64'
name = "vm-0"
maxmem = 2048
memory = 2048
vcpus = 2
maxvcpus = 2
builder = "hvm"
boot = "cd,menu=on,splash=/usr/share/drakrun/splash.jpg,splash-time=2000"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "restart"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0:0,websocket=6400"
vncpasswd="Xlqu3GZreIFXgDowxFRs"
usb = 1
usbdevice = "tablet"
altp2m = 2
shadow_memory = 16
audio=1
soundhw='hda'
cpuid="host,htt=0"
vga="stdvga"
vif = [ 'type=ioemu,model=e1000,bridge=drak0' ]
disk = [ "tap:qcow2:/var/lib/drakrun/volumes/vm-0.img,xvda,w", "file:/opt/win7.iso,hdc:cdrom,r" ]

**Comment by filipi86** [comment]
> /etc/drakrun/configs/vm-0.cfg

I tried two ways, but still this error happen

thor@threat-hunting:/opt$ cat /etc/drakrun/configs/vm-0.cfg

arch = 'x86_64'
name = "vm-0"
maxmem = 3048
memory = 3048
vcpus = 2
maxvcpus = 2
builder = "hvm"
boot = "cd,menu=on,splash=/usr/share/drakrun/splash.jpg,splash-time=2000"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "restart"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0:0,websocket=6400"
vncpasswd="Xlqu3GZreIFXgDowxFRs"
usb = 1
usbdevice = "tablet"
altp2m = 2
shadow_memory = 16
audio=1
soundhw='hda'
cpuid="host,htt=0"
vga="stdvga"
vif = [ 'type=ioemu,model=e1000,bridge=drak0' ]
disk = [ "tap:qcow2:/var/lib/drakrun/volumes/vm-0.img,xvda,w", "file:/opt/win7.iso,hdc:cdrom,r" ]
================================================================================

thor@threat-hunting:/opt$ cat /etc/drakrun/configs/vm-0.cfg
arch = 'x86_64'
name = "vm-0"
maxmem = 2048
memory = 2048
vcpus = 2
maxvcpus = 2
builder = "hvm"
boot = "cd,menu=on,splash=/usr/share/drakrun/splash.jpg,splash-time=2000"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "restart"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0:0,websocket=6400"
vncpasswd="Xlqu3GZreIFXgDowxFRs"
usb = 1
usbdevice = "tablet"
altp2m = 2
shadow_memory = 16
audio=1
soundhw='hda'
cpuid="host,htt=0"
vga="stdvga"
vif = [ 'type=ioemu,model=e1000,bridge=drak0' ]
disk = [ "tap:qcow2:/var/lib/drakrun/volumes/vm-0.img,xvda,w", "file:/opt/win7.iso,hdc:cdrom,r" ]

**Comment by chivay** [comment]
OK, the config looks reasonable. Which debs did you use for the installation?
Was it the lastest release, and which distro? I'll try to reproduce the issue.

**Comment by filipi86** [comment]
Sure...
I tried in Ubuntu and Debian and I used this debs packages.

![Release](https://user-images.githubusercontent.com/31785433/91337272-811ef380-e7a9-11ea-8801-e594dba69cfc.png)

The same recommendation of the Git ..

I'm using VirtualBox - With 4 CPUs - 8Gb RAM and 95 Disk, the Virtualization things enable (VT and more)

**Comment by chivay** [comment]
Oh, that changes everything. Nested virtualization is a tricky subject and not all hypervisors support all features that we require. We  didn't investigate compatibility of drakvuf-sandbox and VirtualBox. From quick search I can see that nested VT-x was merged in VirtualBox 6.1 however I'm not sure if everything is supported.

Our best recommendation would be to try VMware Workstation Player as it's proven itself as capable of running the sandbox.

**Comment by filipi86** [comment]
Ok..
I'll try with VMWare..
However, if is possible, I would like to suggest the usability/homologation with VirtualBox, you know, it is the most common virtualizer..

Thank you again..

**Comment by chivay** [comment]
OK, I've created #221 
Thanks for taking an interest in our project :)

**Comment by filipi86** [comment]
Thank you so much..
I'll follow all updates and I'll make others test with DrakVUF.. 

Thank you for all support..

Filipi Pires

**Comment by filipi86** [comment]
@chivay I used VMWare and It worked 👍
