### ISSUE TITLE
Compatibility study for VirtualBox

### ISSUE THREAD

**Issue by chivay** [CERT-Polska/drakvuf-sandbox#221]
Test if it's possible to run sanbox under VirtualBox or verify missing features.

**Comment by filipi86** [comment]
@chivay  It is possible some test in AWS and Azure environment?..

Probably, I'll try in AWS environment.

**Comment by chivay** [comment]
Running the sandbox in a cloud would be awesome since it would simplify testing, CI and of course running it in production.
However, we've tested most popular clouds: GCP, AWS and Azure and unfortunately none of them was able to run it.  :(

See #93 and #92

**Comment by chivay** [comment]
Tested with VirtualBox 6.1.14 r140239 under Linux:
- nested VMX is working
- missing nested EPT support (no `ept` flag in `lscpu`)
- missing MTF support (`rdmsr --bitfield 59:59 $((0x00000482))` returns 0)

Closing for now.
