### ISSUE TITLE
Documentation on updating DRAKVUF

### ISSUE THREAD

**Issue by devnull044** [CERT-Polska/drakvuf-sandbox#238]
Add documentation to the README or wherever else on how to update to the latest version as new releases are pushed for those who are unfamiliar with the process (kinda me).

Something on the lines of:
- download latest release from repo
- stop all drakvuf services
- run apt get install <updated version of drak>

**Comment by mlodic** [comment]
I was looking for the same thing. 

In general, I think that the documentation does not values the qualities of this project.
