### ISSUE TITLE
Error mount ntfs

### ISSUE THREAD

**Issue by R3n3r0** [CERT-Polska/drakvuf-sandbox#259]
I can't get the postintall to work. I get ntfs mount error. It says the volume does not exist.

**Comment by icedevml** [comment]
@R3n3r0 Could you post the exact full error message?

**Comment by R3n3r0** [comment]
Place the screenshot of the error.
![IMG-20201005-WA0032.jpg](https://user-images.githubusercontent.com/39036500/95128652-09ee5f00-075a-11eb-9619-b8fecf156b92.jpg)

**Comment by icedevml** [comment]
As a workaround you can try:
```
draksetup postinstall --no-usermode
```
to skip this part of setup process (it's optional).

Regarding the original issue, @chivay @BonusPlay could you investigate this?

**Comment by BonusPlay** [comment]
First of all, we need to check why it crashes even tho this part of postinstall is wrapped in 99999 `try: except:`
Second of all - it may be an issue with missing `modprobe ntfs-3g`, as ZFS seems to be working.

**Comment by R3n3r0** [comment]
No ntfs modules are all installed. The problem is that that lvm partition I try to mount is not ntfs or rather the driver does not recognize it as ntfs.

**Comment by R3n3r0** [comment]
As for the exception, you are the one to throw it. In fact I thought it was a fundamental step not optional.
