### ISSUE TITLE
Blank analyses page

### ISSUE THREAD

**Issue by yuriufo** [CERT-Polska/drakvuf-sandbox#277]
**Describe the bug**

After clicking the "analyses" button on the web page, it will jump to http://localhost:6300/.

![analyses](https://user-images.githubusercontent.com/30290025/95933440-285ef500-0e01-11eb-9db2-557ca550133d.png)

But this page is blank page. The html code of this page is as follows:

![图片](https://user-images.githubusercontent.com/30290025/95933494-49bfe100-0e01-11eb-8606-cfeb74d36543.png)

I have completed the entire installation phase and analyzed several samples normally. So this problem appeared suddenly. I tried to clear all the keys of the redis but it didn't work. Is there a way to restore the initialization?

**Comment by icedevml** [comment]
Hello,

thanks for your interest in DRAKVUF Sandbox project!

I belive that you've ran into the bug described here: https://github.com/CERT-Polska/drakvuf-sandbox/pull/264

This is already fixed, but the new version containing fix was not released yet. I'm building a bugfix release now, should be available shortly.

**Workaround:**
1. Navigate to http://localhost:9000/minio/
2. Log in. The credentials are autogenerated and you could check them in `/etc/drakrun/config.ini`, these should be in `access_key` and `secret_key` in section `[minio]`.
3. Go to `drakrun` bucket and entirely delete all folders that don't contain `metadata.json` file (or just delete everything inside that bucket).

**Comment by yuriufo** [comment]
> 
> 
> Hello,
> 
> thanks for your interest in DRAKVUF Sandbox project!
> 
> I belive that you've ran into the bug described here: #264
> 
> This is already fixed, but the new version containing fix was not released yet. I'm building a bugfix release now, should be available shortly.
> 
> **Workaround:**
> 
>     1. Navigate to http://localhost:9000/minio/
> 
>     2. Log in. The credentials are autogenerated and you could check them in `/etc/drakrun/config.ini`, these should be in `access_key` and `secret_key` in section `[minio]`.
> 
>     3. Go to `drakrun` bucket and entirely delete all folders that don't contain `metadata.json` file (or just delete everything inside that bucket).

It works! :) thank you!

**Comment by icedevml** [comment]
And here is the fixed release:

https://github.com/CERT-Polska/drakvuf-sandbox/releases/tag/v0.10.2

generally it should be enough that you download `<your_distribution>_drakcore_0.10.0_amd64.deb` package and install it with `dpkg -i <filename>.deb`. Then, execute `systemctl restart drak-web` and the issue should be permanently fixed.

**Comment by icedevml** [comment]
Closing this as the problem was solved. Feel free to reopen if the problem still occurs.

**Comment by yuriufo** [comment]
> 
> 
> And here is the fixed release:
> 
> https://github.com/CERT-Polska/drakvuf-sandbox/releases/tag/v0.10.2
> 
> generally it should be enough that you download `<your_distribution>_drakcore_0.10.0_amd64.deb` package and install it with `dpkg -i <filename>.deb`. Then, execute `systemctl restart drak-web` and the issue should be permanently fixed.

After I updated in this way, the following problems occurred:

```
$ sudo drak-healthcheck
Checking daemon status...
drak-web.service              OK
drak-system.service           ERROR
drak-minio.service            OK
drak-postprocess.service      OK

Checking worker status...
drakrun@1.service             ERROR
```

And I followed ![upgrading](https://drakvuf-sandbox.readthedocs.io/en/latest/usage/upgrading.html) and got the same error.

**Comment by icedevml** [comment]
Could you show `journalctl -u drak-system`?

**Comment by yuriufo** [comment]
> 
> 
> Could you show `journalctl -u drak-system`?

```
10月 14 11:18:29 sandbox systemd[1]: Stopped drak-system service.
10月 14 11:18:29 sandbox systemd[1]: Started drak-system service.
10月 14 11:18:29 sandbox drak-system[936]: [2020-10-14 11:18:29,927][INFO] Verifying bucket existence...
10月 14 11:18:29 sandbox drak-system[936]: Traceback (most recent call last):
10月 14 11:18:29 sandbox drak-system[936]:   File "/opt/venvs/drakcore/bin/drak-system", line 4, in <module>
10月 14 11:18:29 sandbox drak-system[936]:     main()
10月 14 11:18:29 sandbox drak-system[936]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/system.py", line 36, in main
10月 14 11:18:29 sandbox drak-system[936]:     if not minio.bucket_exists(bucket_name):
10月 14 11:18:29 sandbox drak-system[936]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/minio/api.py", line 423, in bucket_exists
10月 14 11:18:29 sandbox drak-system[936]:     self._url_open('HEAD', bucket_name=bucket_name)
10月 14 11:18:29 sandbox drak-system[936]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/minio/api.py", line 1922, in _url_open
10月 14 11:18:29 sandbox drak-system[936]:     region = self._get_bucket_region(bucket_name)
10月 14 11:18:29 sandbox drak-system[936]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/minio/api.py", line 1852, in _get_bucket_region
10月 14 11:18:29 sandbox drak-system[936]:     region = self._get_bucket_location(bucket_name)
10月 14 11:18:29 sandbox drak-system[936]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/minio/api.py", line 1894, in _get_bucket_location
10月 14 11:18:29 sandbox drak-system[936]:     raise ResponseError(response, method, bucket_name).get_exception()
10月 14 11:18:29 sandbox drak-system[936]: minio.error.InvalidAccessKeyId: InvalidAccessKeyId: message: The access key Id you provided does not exist in our records.
10月 14 11:18:29 sandbox systemd[1]: drak-system.service: Main process exited, code=exited, status=1/FAILURE
10月 14 11:18:29 sandbox systemd[1]: drak-system.service: Failed with result 'exit-code'.
10月 14 11:18:35 sandbox drak-system[990]: [2020-10-14 11:18:35,112][INFO] Verifying bucket existence...
10月 14 11:18:35 sandbox drak-system[990]: Traceback (most recent call last):
10月 14 11:18:35 sandbox drak-system[990]:   File "/opt/venvs/drakcore/bin/drak-system", line 4, in <module>
10月 14 11:18:35 sandbox drak-system[990]:     main()
10月 14 11:18:35 sandbox drak-system[990]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/system.py", line 36, in main
10月 14 11:18:35 sandbox drak-system[990]:     if not minio.bucket_exists(bucket_name):
10月 14 11:18:35 sandbox drak-system[990]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/minio/api.py", line 423, in bucket_exists
10月 14 11:18:35 sandbox drak-system[990]:     self._url_open('HEAD', bucket_name=bucket_name)
10月 14 11:18:35 sandbox drak-system[990]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/minio/api.py", line 1922, in _url_open
10月 14 11:18:35 sandbox drak-system[990]:     region = self._get_bucket_region(bucket_name)
10月 14 11:18:35 sandbox drak-system[990]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/minio/api.py", line 1852, in _get_bucket_region
10月 14 11:18:35 sandbox drak-system[990]:     region = self._get_bucket_location(bucket_name)
10月 14 11:18:35 sandbox drak-system[990]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/minio/api.py", line 1894, in _get_bucket_location
10月 14 11:18:35 sandbox drak-system[990]:     raise ResponseError(response, method, bucket_name).get_exception()
10月 14 11:18:35 sandbox drak-system[990]: minio.error.InvalidAccessKeyId: InvalidAccessKeyId: message: The access key Id you provided does not exist in our records.
10月 14 11:18:34 sandbox systemd[1]: drak-system.service: Scheduled restart job, restart counter is at 2.
10月 14 11:18:34 sandbox systemd[1]: Stopped drak-system service.
10月 14 11:18:34 sandbox systemd[1]: Started drak-system service.
10月 14 11:18:35 sandbox systemd[1]: drak-system.service: Main process exited, code=exited, status=1/FAILURE
10月 14 11:18:35 sandbox systemd[1]: drak-system.service: Failed with result 'exit-code'.
10月 14 11:18:40 sandbox systemd[1]: drak-system.service: Scheduled restart job, restart counter is at 3.
10月 14 11:18:40 sandbox systemd[1]: Stopped drak-system service.
10月 14 11:18:40 sandbox systemd[1]: drak-system.service: Start request repeated too quickly.
10月 14 11:18:40 sandbox systemd[1]: drak-system.service: Failed with result 'exit-code'.
10月 14 11:18:40 sandbox systemd[1]: Failed to start drak-system service.
```

**Comment by icedevml** [comment]
Please look at `/etc/drakcore/minio.env` and compare whether the credentials match with `[minio]` `access_key` and `secret_key` in `/etc/drakcore/config.ini` and `/etc/drakrun/config.ini`. If not, please correct this so the credentials are the same in all these three files.

Then:
```
systemctl restart drak-minio
systemctl restart drak-system
systemctl restart drak-web
systemctl restart drak-postprocess
systemctl restart drakrun@1
```

let me know if it helped.

This desync of credentials after upgrade is another bug and we will investigate it.

**Comment by yuriufo** [comment]
> 
> 
> Please look at `/etc/drakcore/minio.env` and compare whether the credentials match with `[minio]` `access_key` and `secret_key` in files `/etc/drakcore/config.ini` and `/etc/drakrun/config.ini`. If not, please correct this so the credentials are the same in all these three files.
> 
> Then:
> 
> ```
> systemctl restart drak-minio
> systemctl restart drak-system
> systemctl restart drak-web
> systemctl restart drak-postprocess
> systemctl restart drakrun@1
> ```
> 
> let me know if it helped.
> 
> This desync of credentials after upgrade is another bug and we will investigate it.

These three files‘ key are indeed different. I corrected them and solved all problems.

**Comment by icedevml** [comment]
Closing as this was fixed, the issue with upgrading will be investigated in #283
