### ISSUE TITLE
Push_sample.py default port to push to

### ISSUE THREAD

**Issue by Latanyor** [CERT-Polska/drakvuf-sandbox#282]
in the example for pushing a sample from the commandline to the analysis, the url `http://localhost:5000` is default. 
When i try to push to that url I get a `Connection failed to http://localhost:5000` message.

Why is the default port `5000` and not `6300/upload`? 

when pushing there, is does work, but the regex from #239 does prevent me from pushing samples which are in another directory or don't have a file extension.

**Comment by icedevml** [comment]
Hello, thanks for reporting, we will investigate this.
