### ISSUE TITLE
drakrun: change the way of vm-X.cfg generation, drop --max-vms

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/drakvuf-sandbox#314]
We need to give more control over drakrun replication, it's too magic right now.

Proposal:

* remove `--max-vms`
* generate `vm-X.cfg` upon startup of `drakrun@X` service, not during `postinstall`
* add comment in `vm-X.cfg` to discourage from editing the file directly (template should be used instead)
* don't enable drakrun service by default
* don't start drakrun by default
* `drak-healthcheck` - show statuses of enabled `drakrun@X` services

**Comment by chivay** [comment]
Makes sense :+1: 

IMO, `vm-x.cfg` files can even be made ephemeral and regenerated each time they're going to be used. This will ensure that only template would be modified
