### ISSUE TITLE
Trim trailing zero bytes from dumps

### ISSUE THREAD

**Issue by catsuryuu** [CERT-Polska/drakvuf-sandbox#325]
Drakvuf sometimes produces a dump with a lot of zero bytes at the end (e.g. 100kk zeros).

I think these zero bytes should be trimmed (all of them or at least majority of them).

**Comment by kscieslinski** [comment]
Can we move this issue to [drakvuf](https://github.com/tklengyel/drakvuf)? If we want to trim zeros we should do this at the memdump plugin level. I think this is not a real issue for now as the drakvuf-sandbox performs [compression](https://github.com/CERT-Polska/drakvuf-sandbox/blob/1b61996cbe45a153608de872f48e7eb0195c99c3/drakrun/drakrun/main.py#L171) on these dumps.

**Comment by icedevml** [comment]
Sometimes we create an issue here, tag it `drakvuf-bundle` and the final PR is made towards `drakvuf` repository. This is usually done when the problem is specific to DRAKVUF Sandbox.

**Comment by catsuryuu** [comment]
It turned out that in my case some of these zeros (about 2-3 millions) was a part of the import table, so it looks like dumps shouldn't be simply trimmed of all trailing zeros.
