### ISSUE TITLE
System runs into soft lockup while analysis

### ISSUE THREAD

**Issue by Latanyor** [CERT-Polska/drakvuf-sandbox#328]
**Problem description**
While running a analysis my system run into a _soft lockup_ several times. The console is responsive at first, but gets unresponsive after a short time. Needed to reset the reboot the system manually to get it running again.

**Further information**
It's not reproducable everytime, but the last 3 times I ran a agentTesla sample ( SHA256: `006449caaa797b90e1c58ff7a1a767a937e220b45f98cb9f55a0227a2a1d7f08`), the system crashed. 
Happend with other families and sample files also.
The anaylsis does run for circa 5 minutes and then the system runs into the lock:
```
2020-10-27 11:15:41,671 DEBUG    main                           Status for e9f69119-e69d-45d1-bc3a-5f0ab83cc6dc: pending
2020-10-27 11:15:41,671 INFO     main                           Waiting for the task e9f69119-e69d-45d1-bc3a-5f0ab83cc6dc to finish... Waiting since 4.5 minutes
2020-10-27 11:16:11,704 DEBUG    main                           Status for e9f69119-e69d-45d1-bc3a-5f0ab83cc6dc: pending
2020-10-27 11:16:11,704 INFO     main                           Waiting for the task e9f69119-e69d-45d1-bc3a-5f0ab83cc6dc to finish... Waiting since 5.0 minutes
```

At the time of the lock, the load on one of the CPU cores is at 100%:
![softlock_100percent_red_cut](https://user-images.githubusercontent.com/35563666/97304276-cc15bf80-185b-11eb-9045-e8823d1b4627.jpg)
![softlock_agenttesla_cut](https://user-images.githubusercontent.com/35563666/97305051-e13f1e00-185c-11eb-8727-f8a8f3c3936d.jpg)

Thats what I got on the console at the time of the softlock:
```
Message from syslogd@milano at Oct 27 10:28:04 ...
 kernel:[84276.744692] watchdog: BUG: soft lockup - CPU#16 stuck for 22s! [kworker/16:1:142]

Message from syslogd@milano at Oct 27 10:28:32 ...
 kernel:[84304.743699] watchdog: BUG: soft lockup - CPU#16 stuck for 22s! [kworker/16:1:142]

Message from syslogd@milano at Oct 27 10:29:08 ...
 kernel:[84340.742340] watchdog: BUG: soft lockup - CPU#16 stuck for 23s! [kworker/16:1:142]
```

**System info**
Here are some details about my system:
- The system is a DELL PowerEdge R540.
- Os is  Debian 10.
- running DRAKVUF-Sandbox at version `0.10.2` (did also happen to me on version `0.8` and `0.9`)
```
# uname
Linux 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 48 bits virtual
CPU(s):              20
On-line CPU(s) list: 0-19
Thread(s) per core:  20
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
Stepping:            4
CPU MHz:             2194.870
BogoMIPS:            4389.74
Hypervisor vendor:   Xen
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            14080K
NUMA node0 CPU(s):   0-19
Flags:               fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid pni pclmulqdq monitor est ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp fsgsbase bmi1 hle avx2 bmi2 erms rtm avx512f avx512dq rdseed adx clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 md_clear
```
*** Gues ***
The lock seems to appear at the end of the analysis, when the `vm-1` is shut down, but that's only a gues.

**Comment by icedevml** [comment]
> DELL PowerEdge R540.

We are debugging our PowerEdge R640 just right now as well, I guess this is the same issue.

Could you post your `xl info`?

**Comment by icedevml** [comment]
If your `xl info` shows:

```
xen_scheduler          : credit2
```

then:

**Workaround**
1. Add `sched=credit` to `GRUB_CMDLINE_XEN_DEFAULT` in `/etc/default/grub.d/xen.cfg`
2. Execute `update-grub`
3. Reboot machine

please confirm if this is the case.

**Comment by Latanyor** [comment]
I have a couple of analysis in the pipeline but will try as soon as thats finished 👍🏻

**Comment by Latanyor** [comment]
Seems to have done the trick. At least I don't get a lock anymore.

**Comment by icedevml** [comment]
Thanks for confirming. There is a discussion on `xen-devel` about possible regressions with Xen 4.14 and it seems it might be related to `sched=credit2`. We still don't know whether this is the actual problem in the scheduler or whether it just dodges the bug. For the moment we will stick to this workaround.

**Comment by Latanyor** [comment]
Thanks for the quick fix. Will watch out for further updates on that.

**Comment by icedevml** [comment]
Closing as fixed for now, feel free to reopen if there is an issue again.

**Comment by icedevml** [comment]
related https://lists.xen.org/archives/html/xen-devel/2020-10/msg01561.html
