### ISSUE TITLE
Allow to clone drakrun state across servers

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/drakvuf-sandbox#356]
We could support two ways of cloning:

* One-to-one clone - copy the VM snapshot as well as disk and JSON profiles, might fail if the source hardware differs from target hardware (basically this is going to work if you have 2 identical servers)
* Disk clone - copy the disk image of the VM that is powered off, then start it and perform `draksetup postinstall` normally

**Comment by chivay** [comment]
closed by #376
