### ISSUE TITLE
Use appropriate drakvuf-bundle when building drakrun package in CI

### ISSUE THREAD

**Issue by chivay** [CERT-Polska/drakvuf-sandbox#365]
We're downloading an external package. This step should depend on and use drakvuf-bundle built during CI execution.
https://github.com/CERT-Polska/drakvuf-sandbox/blob/master/.drone.yml#L95

**Comment by catsuryuu** [comment]
According to #674, we no longer download the external package, but the URL is still constant and written manually. 
https://github.com/CERT-Polska/drakvuf-sandbox/blob/66b474e416c487e177594fba37040b909d0b107a/.drone.yml#L106
