### ISSUE TITLE
Support for .rtf files

### ISSUE THREAD

**Issue by BonusPlay** [CERT-Polska/drakvuf-sandbox#397]
Word can already open those files, only need to add association for startup command.

**Comment by techathena** [comment]
are you talking about a python script which associated rtf files to word by default? or something else?

**Comment by BonusPlay** [comment]
I'm refering to a proper startup command for those files, which will be executed after the file is injected into the VM.
https://github.com/CERT-Polska/drakvuf-sandbox/blob/master/drakrun/drakrun/main.py#L231-L243 should clear stuff a bit.

**Comment by techathena** [comment]
I can see a function is already defined for word files opening word file , so just adding the .rtf extension to this https://github.com/CERT-Polska/drakvuf-sandbox/blob/bb5e4501652c317b6e72d6ff1f9060b56eab3031/drakrun/drakrun/office.py#L311
should work. Am I right ?(or is there anything else I am missing?)

**Comment by chivay** [comment]
@techathena yup, I think that it should work :+1:
