### ISSUE TITLE
(XEN) VMX: CPU0 has insufficient CPU-Based Exec Control (b5b9fffe; requires 2299968c)

### ISSUE THREAD

**Issue by MurbieDev** [CERT-Polska/drakvuf-sandbox#418]
Good Morning! I have been trying to get DRAKVUF Sandbox GUI set up following the steps outlined in "Getting Started" for a basic installation. I am running Ubuntu Bionic 18.04.5 on VMware Fusion 12.1.0 with 2 processor cores and 8GB of RAM. I have enabled VT-x/EPT support as well as IOMMU.

Prior to installing the drakvuf bundle, running lscpu indicates that VMX and EPT are both enabled. Once I install the bundle and reboot into the Xen hypervisor instance, I install drakcore and drakrun without any issues. Running draksetup install <path to iso> results in the following output:

> root@ubuntu:/home/ccre/Downloads# draksetup install Win_7_SP1_32BIT.ISO
/opt/venvs/drakrun/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[2021-01-14 09:09:22,007][INFO] Ensuring that drakrun@* services are stopped...
[2021-01-14 09:09:22,031][INFO] Performing installation...
[2021-01-14 09:09:38,152][INFO] Checking xen-detect...
Running in PV context on Xen V4.14.
[2021-01-14 09:09:38,165][INFO] Testing if xl tool is sane...
[2021-01-14 09:09:38,232][INFO] Generated VM configuration for vm-0
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
Parsing config from /etc/drakrun/configs/vm-0.cfg
libxl: error: libxl_create.c:671:libxl__domain_make: domain creation fail: Invalid argument
libxl: error: libxl_create.c:1233:initiate_domain_create: cannot make domain: -3
[2021-01-14 09:09:38,668][ERROR] Failed to launch VM vm-0
Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 183, in install
    subprocess.run('xl create {}'.format(shlex.quote(cfg_path)), shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'xl create /etc/drakrun/configs/vm-0.cfg' returned non-zero exit status 3.

This error message led me to investigate the xl dmesg output to see what the actual issue may be. I also checked to see if /var/log/xen/qemu*.log was generated, but nothing was generated.

> root@ubuntu: xl dmesg
Xen 4.14.0
(XEN) Xen version 4.14.0 (root@) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0) debug=n  Thu Jan 14 12:44:18 UTC 2021
(XEN) Latest ChangeSet: 
(XEN) Bootloader: GRUB 2.02-2ubuntu8.17
(XEN) Command line: placeholder dom0_mem=3966M,max:3966M dom0_max_vcpus=1 dom0_vcpus_pin=1 force-ept=1 ept=pml=0 hap_1gb=0 hap_2mb=0 altp2m=1 smt=0 sched=credit
(XEN) Xen image load base address: 0
(XEN) Video information:
(XEN)  VGA is text mode 80x25, font 8x16
(XEN) Disc information:
(XEN)  Found 1 MBR signatures
(XEN)  Found 1 EDD information structures
(XEN) Xen-e820 RAM map:
(XEN)  [0000000000000000, 000000000009e7ff] (usable)
(XEN)  [000000000009e800, 000000000009ffff] (reserved)
(XEN)  [00000000000dc000, 00000000000fffff] (reserved)
(XEN)  [0000000000100000, 00000000bfecffff] (usable)
(XEN)  [00000000bfed0000, 00000000bfefefff] (ACPI data)
(XEN)  [00000000bfeff000, 00000000bfefffff] (ACPI NVS)
(XEN)  [00000000bff00000, 00000000bfffffff] (usable)
(XEN)  [00000000f0000000, 00000000f7ffffff] (reserved)
(XEN)  [00000000fec00000, 00000000fec0ffff] (reserved)
(XEN)  [00000000fee00000, 00000000fee00fff] (reserved)
(XEN)  [00000000fffe0000, 00000000ffffffff] (reserved)
(XEN)  [0000000100000000, 000000023fffffff] (usable)
(XEN) New Xen image base address: 0xbf800000
(XEN) ACPI: RSDP 000F6A00, 0024 (r2 PTLTD )
(XEN) ACPI: XSDT BFEDB5D7, 0064 (r1 INTEL  440BX     6040000 VMW   1324272)
(XEN) ACPI: FACP BFEFEE73, 00F4 (r4 INTEL  440BX     6040000 PTL     F4240)
(XEN) ACPI: DSDT BFEDD001, 21E72 (r1 PTLTD  Custom    6040000 MSFT  3000001)
(XEN) ACPI: FACS BFEFFFC0, 0040
(XEN) ACPI: BOOT BFEDCFB4, 0028 (r1 PTLTD  $SBFTBL$  6040000  LTP        1)
(XEN) ACPI: APIC BFEDC872, 0742 (r1 PTLTD  	 APIC    6040000  LTP        0)
(XEN) ACPI: MCFG BFEDC836, 003C (r1 PTLTD  $PCFGCITBL$  6040000  LTP        1)
(XEN) ACPI: SRAT BFEDB72F, 08D0 (r2 VMWARE MEMPLUG   6040000 VMW         1)
(XEN) ACPI: HPET BFEDB6F7, 0038 (r1 VMWARE VMW HPET  6040000 VMW         1)
(XEN) ACPI: WAET BFEDB6CF, 0028 (r1 VMWARE VMW WAET  6040000 VMW         1)
(XEN) ACPI: DMAR BFEDB67F, 0050 (r1 VMWARE VMW DMAR  6040000 VMW         1)
(XEN) System RAM: 8191MB (8388024kB)
(XEN) Domain heap initialised
(XEN) IOAPIC[0]: apic_id 1, version 32, address 0xfec00000, GSI 0-23
(XEN) Enabling APIC mode:  Phys.  Using 1 I/O APICs
(XEN) Switched to APIC driver x2apic_phys
(XEN) xstate: size: 0x340 and states: 0x7
(XEN) Speculative mitigation facilities:
(XEN)   Hardware features: IBRS/IBPB STIBP L1D_FLUSH SSBD MD_CLEAR IBRS_ALL RDCL_NO SKIP_L1DFL MDS_NO
(XEN)   Compiled-in support: INDIRECT_THUNK SHADOW_PAGING
(XEN)   Xen settings: BTI-Thunk JMP, SPEC_CTRL: IBRS+ SSBD-, Other: IBPB BRANCH_HARDEN
(XEN)   Support for HVM VMs: MSR_SPEC_CTRL RSB EAGER_FPU MD_CLEAR
(XEN)   Support for PV VMs: MSR_SPEC_CTRL RSB EAGER_FPU MD_CLEAR
(XEN)   XPTI (64-bit PV only): Dom0 disabled, DomU disabled (with PCID)
(XEN)   PV L1TF shadowing: Dom0 disabled, DomU disabled
(XEN) Using scheduler: SMP Credit Scheduler (credit)
(XEN) Platform timer is 14.318MHz HPET
(XEN) Detected 2304.038 MHz processor.
(XEN) Intel VT-d iommu 0 supported page sizes: 4kB
(XEN) Intel VT-d Snoop Control not enabled.
(XEN) Intel VT-d Dom0 DMA Passthrough not enabled.
(XEN) Intel VT-d Queued Invalidation enabled.
(XEN) Intel VT-d Interrupt Remapping enabled.
(XEN) Intel VT-d Posted Interrupt not enabled.
(XEN) Intel VT-d Shared EPT tables enabled.
(XEN) I/O virtualisation enabled
(XEN)  - Dom0 mode: Relaxed
(XEN) Interrupt remapping enabled
(XEN) ENABLING IO-APIC IRQs
(XEN)  -> Using new ACK method
(XEN) Allocated console ring of 16 KiB.
(XEN) VMX: CPU0 has insufficient CPU-Based Exec Control (b5b9fffe; requires 2299968c)
(XEN) VMX: failed to initialise.
(XEN) Brought up 2 CPUsCFG
(XEN) Scheduling granularity: cpu, 1 CPU per sched-resource
(XEN) Dom0 has maximum 232 PIRQs
(XEN)  Xen  kernel: 64-bit, lsb, compat32
(XEN)  Dom0 kernel: 64-bit, PAE, lsb, paddr 0x1000000 -> 0x3600000
(XEN) PHYSICAL MEMORY ARRANGEMENT:
(XEN)  Dom0 alloc.:   0000000230000000->0000000234000000 (988823 pages to be allocated)
(XEN)  Init. ramdisk: 000000023d897000->000000023ffff8df
(XEN) VIRTUAL MEMORY ARRANGEMENT:
(XEN)  Loaded kernel: ffffffff81000000->ffffffff83600000
(XEN)  Init. ramdisk: 0000000000000000->0000000000000000
(XEN)  Phys-Mach map: 0000008000000000->00000080007bf000
(XEN)  Start info:    ffffffff83600000->ffffffff836004b8
(XEN)  Xenstore ring: 0000000000000000->0000000000000000
(XEN)  Console ring:  0000000000000000->0000000000000000
(XEN)  Page tables:   ffffffff83601000->ffffffff83620000
(XEN)  Boot stack:    ffffffff83620000->ffffffff83621000
(XEN)  TOTAL:         ffffffff80000000->ffffffff83800000
(XEN)  ENTRY ADDRESS: ffffffff82898180
(XEN) Dom0 has maximum 1 VCPUs
(XEN) Initial low memory virq threshold set at 0x4000 pages.
(XEN) Scrubbing Free RAM in background
(XEN) Std. Loglevel: Errors and warnings
(XEN) Guest Loglevel: Nothing (Rate-limited: Errors and warnings)
(XEN) Xen is relinquishing VGA console.
(XEN) *** Serial input to DOM0 (type 'CTRL-a' three times to switch input)
(XEN) Freed 560kB init memory

More specifically, in the output above, you can see that there was an error with the CPU.

> (XEN) VMX: CPU0 has insufficient CPU-Based Exec Control (b5b9fffe; requires 2299968c)
(XEN) VMX: failed to initialise.

I tried searching online to see if there were any instances of this problem occurring without any luck. I have also tried this on Debian 10 Buster and ended up with the exact same error. Both instances I have used the respective 0.8 Debian package for each OS. I've included the config file info below in case it is needed.

> root@ubuntu:/home/ccre/Downloads# cat /etc/drakrun/configs/vm-0.cfg
arch = 'x86_64'
name = "vm-0"
maxmem = 3048
memory = 3048
vcpus = 2
maxvcpus = 2
type = "hvm"
boot = "cd,menu=on,splash=/usr/share/drakrun/splash.jpg,splash-time=2000"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "restart"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0:0,websocket=6400"
vncpasswd="zP5dn11iJtoGoKVIIT0J"
usb = 1
usbdevice = "tablet"
altp2m = 2
shadow_memory = 16
audio=1
soundhw='hda'
cpuid="host,htt=0"
vga="stdvga"
vif = [ 'type=ioemu,model=e1000,bridge=drak0' ]
disk = [ "tap:qcow2:/var/lib/drakrun/volumes/vm-0.img,xvda,w", "file:/home/ccre/Downloads/Win_7_SP1_32BIT.ISO,hdc:cdrom,r" ]
processor_trace_buf_kb = 65536

Any assistance or insight on this matter would be greatly appreciated.

Thanks,
Kyle

**Comment by BonusPlay** [comment]
Hello! It seems that the CPU is missing a bit (nr. 25 to be precise). According to Intel SDM:

![image](https://user-images.githubusercontent.com/8405359/104635137-ce8cf600-56a1-11eb-8780-75917b48498d.png)

This may be caused by either CPU being too old or VMware Fusion 12.1.0 not supporting that specific feature. For obvious reasons I'd recommend trying newer version of VMware before blaming the hardware. Could you provide exact CPU model as well? That would help narrowing the issue.

**Comment by MurbieDev** [comment]
I appreciate the quick response!

VMware is updated to the latest available version, so not much to do on that front. I am curious if you think it may be because it is VMware Fusion Pro (running on an Apple Laptop) rather than running on a Windows-based machine with VMWare Pro.

The CPU in use is a 2.3GHz 8-core 9th-generation Intel Core i9 processor.

Thanks,
Kyle

**Comment by BonusPlay** [comment]
We haven't tested drakvuf-sandbox on apple machines at all, so my initial thought is that VMware Fusion might be incompatible with drakvuf-sandbox.

**Comment by MurbieDev** [comment]
Man, that is a real bummer. I am going to try and investigate whether VMware Fusion vs VMware Workstation Pro has any differences in capabilities/support.  How were you able to determine that the CPU was missing a bit? I'd like to submit a ticket to VMware Fusion about this.

I'll also try and install on VMware Workstation Pro on a relatively new Intel processor to see if I run into any issues.

Thank you so much!
Kyle

**Comment by chivay** [comment]
Hi,

>How were you able to determine that the CPU was missing a bit? 

We've got it from Xen error:
```
(XEN) VMX: CPU0 has insufficient CPU-Based Exec Control (b5b9fffe; requires 2299968c)
```
Thus we can compute

```
>>> wants = 0x2299968c
>>> has = 0xb5b9fffe
>>> missing = (wants & has) ^ wants
>>> hex(missing)
'0x2000000'
>>> 1 << 25 == missing
True
```

Then we've looked up  `24.6.2 Processor-Based VM-Execution Controls` in Intel SDM  (Table 24-6. Definitions of Primary Processor-Based VM-Execution Controls)

As far as I know, this feature isn't directly used by DRAKVUF, however from a quick look at Xen source code it seems that this flag is required for booting a HVM (hardware virtualized machine) domain:

https://github.com/xen-project/xen/blob/0293fd24bbaa2c4fa0acbe2abcd2d41b96ecd7e1/xen/arch/x86/hvm/vmx/vmcs.c#L279

It may be a limitation of the hypervisor API of OS X although I don't have enough experience with Apple platform to confirm it. 

If you don't have any other hardware to test, my recommendation would be to try one of the tested bare metal server providers, see:
https://drakvuf-sandbox.readthedocs.io/en/latest/faq.html#can-i-run-drakvuf-sandbox-in-the-cloud

Hubert

**Comment by icedevml** [comment]
Patch posted to xen-devel by @chivay 
https://lore.kernel.org/xen-devel/570e73b83c18cce4dbe4c70cc14b6df7c33f0502.1610720991.git.hubert.jasudowicz@cert.pl/T/#u

**Comment by chivay** [comment]
Hi @MurbieDev, 
can you try this version of drakvuf bundle:
https://debs.icedev.pl/debs/drakvuf-bundle-1e61581d1b80431b31384acc8bd0871747f18c14.deb

It should fix the issue with missing IO bitmap feature flag.

**Comment by MurbieDev** [comment]
Thank you @chivay, @icedevml, and @BonusPlay for your detailed responses.

I tried the version of drakvuf bundle @chivay provided above on Ubuntu Bionic. 18.04.5 and the setup moved past the initial error, but hung on "Testing if xl tool is sane...". I've included the output below:

> root@ubuntu:/home/ccre/Downloads# draksetup install SW_DVD9_Win_Pro_10_20H2.2_32BIT_English_Pro_Ent_EDU_N_MLF_-2_X22-46650.ISO
/opt/venvs/drakrun/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[2021-01-15 08:59:45,738][INFO] Ensuring that drakrun@* services are stopped...
[2021-01-15 08:59:45,762][INFO] Performing installation...
[2021-01-15 09:00:07,940][INFO] Checking xen-detect...
Running in PV context on Xen V4.14.
[2021-01-15 09:00:07,950][INFO] Testing if xl tool is sane...

Then I went ahead and tested this on Debian Buster. The VM instance was successfully created!! It is clear that making the 25th bit optional resolves the issue. See output below.

> root@ccre:/home/ccre/Downloads# draksetup install Win_7_SP1_32BIT.ISO
/opt/venvs/drakrun/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
[2021-01-15 11:04:51,423][INFO] Ensuring that drakrun@* services are stopped...
[2021-01-15 11:04:51,438][INFO] Performing installation...
[2021-01-15 11:05:03,225][INFO] Checking xen-detect...
Running in PV context on Xen V4.14.
[2021-01-15 11:05:03,235][INFO] Testing if xl tool is sane...
[2021-01-15 11:05:03,300][INFO] Generated VM configuration for vm-0
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
Parsing config from /etc/drakrun/configs/vm-0.cfg
[2021-01-15 11:05:04,879][INFO] --------------------------------------------------------------------------------
[2021-01-15 11:05:04,880][INFO] Initial VM setup is complete and the vm-0 was launched.
[2021-01-15 11:05:04,880][INFO] Please now VNC to the port 5900 on this machine to perform Windows installation.
[2021-01-15 11:05:04,880][INFO] After you have installed Windows and booted it to the desktop, please execute:
[2021-01-15 11:05:04,880][INFO] # draksetup postinstall
[2021-01-15 11:05:04,881][INFO] Your configured VNC password is:
[2021-01-15 11:05:04,881][INFO] pvmgPBxzVjIIUl88owWt
[2021-01-15 11:05:04,882][INFO] Please note that on some machines, system installer may boot for up to 10 minutes
[2021-01-15 11:05:04,882][INFO] and may look unresponsive during the process. Please be patient.
[2021-01-15 11:05:04,882][INFO] --------------------------------------------------------------------------------

However, when I attempt to VNC into the VM, I am getting an error stating that the display cannot be opened as shown below. I intend to test the unattended installation to see if it makes a difference in allowing me to connect to the VM. I wanted to respond to your assistance and ask if there may be something obvious that I am missing.

> root@ccre:/home/ccre/Downloads# vncviewer localhost:5900
TigerVNC Viewer 64-bit v1.9.0
Built on: 2020-09-29 18:21
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.
Can't open display:

Again, your assistance is greatly appreciated! Forward progress is being made. 👍 

Cheers,
Kyle

**Comment by chivay** [comment]
Hi,
if you're running it inside virtual machine, you should use a VNC app on your host and connect to  `[VM ip]:5900`.
The error means that vncviewer tried to connect do X display server (which isn't running in your VM)

**Comment by MurbieDev** [comment]
Oddly enough the issue was that I was running vncviewer as root. Running it as user worked like a charm. I ran into booting issues with a Win7 ISO, but Win10 is letting me go through the installation process without any issues.

Thank you so much for all of your help with the setup! I appreciate it.

**Comment by chivay** [comment]
Use `draksetup install --disk-size ?G ` to override default value. However this is somewhat suspicious as the default is 100GB. Are you sure that the Debian VM has enough disk space?

**Comment by MurbieDev** [comment]
You were correct! Increasing the size seemed to do the trick. I've been trying to resolve an issue where the mouse and keyboard no longer functions once the Windows 10 installation is complete. Any chance this is a known issue?

Thanks,
Kyle

**Comment by icedevml** [comment]
I know about this bug, usually it ended up that keyboard was still working, while mouse was not. I think this only affects Windows 10 and I have absolutely no idea why is it so.

**Comment by MurbieDev** [comment]
You are correct - the keyboard works. I can see that pressing tab moves the indicator around the screen. Very odd that the mouse just doesn't.

Due to that error, I decided to shift gears to Windows 7 as I want to simply get drakvuf to work. I get an error that said the Win7 32-bit ISO isn't a bootable disk. I'm going to try and find another ISO in case I got a corrupted copy somehow. 

<img width="723" alt="Screen Shot 2021-01-20 at 7 06 40 AM" src="https://user-images.githubusercontent.com/77453429/105186951-7a45a400-5aef-11eb-8f5d-b01bafaa8a41.png">

**Comment by chivay** [comment]
Hi @MurbieDev, just to make sure that our code is working properly, can you paste the contents of `/etc/drakrun/configs/vm-0.cfg`?

There should be an entry similar to:
```
disk = [ "tap:qcow2:/var/lib/drakrun/volumes/vm-0.img,xvda,w", "file:/root/SW_DVD5_Win_Pro_7w_SP1_64BIT_Polish_-2_MLF_X17-59386.ISO,hdc:cdrom,r" ]
```

with the `file:` pointing to the location of your ISO

**Comment by MurbieDev** [comment]
Hello! Please see below for the contents of the requested file.

> arch = 'x86_64'
name = "vm-0"
maxmem = 3048
memory = 3048
vcpus = 2
maxvcpus = 2
type = "hvm"
boot = "cd,menu=on,splash=/usr/share/drakrun/splash.jpg,splash-time=2000"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "restart"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0:0,websocket=6400"
vncpasswd="VpERhQoL8OB6g1E8liYu"
usb = 1
usbdevice = "tablet"
altp2m = 2
shadow_memory = 16
audio=1
soundhw='hda'
cpuid="host,htt=0"
vga="stdvga"
vif = [ 'type=ioemu,model=e1000,bridge=drak0' ]
disk = [ "tap:qcow2:/var/lib/drakrun/volumes/vm-0.img,xvda,w", "file:/home/ccre/Downloads/Win_7_SP1_32BIT.ISO,hdc:cdrom,r" ]
processor_trace_buf_kb = 65536

I think that the issue may be that the Win7 ISO that I have is not a "bootable" copy. As you can see, yours is a DVD whereas mine is just a straight ISO and during the boot process, it attempts to reach out to ipxe for wimboot, which helps configure the ISO into a bootable disk.  Enabling guest Internet access did not seem to do the trick.

Is there any chance that you guys can simply share a copy of your ISO with me? I am having difficulty finding another copy somewhere else.

Much appreciated!
Kyle

**Comment by chivay** [comment]
huh, that's weird. what's the origin of the 32bit windows 7? is it custom made or straight from MS site?

**Comment by MurbieDev** [comment]
It was taken straight from the MS site. Just as the 64 bit one was.

Win 7 64 bit works without any issues. I am able to upload samples through the GUI now.

I appreciate all of your help and will certainly continue to come back here if I run into any further bugs/issues.

**Comment by MurbieDev** [comment]
Good Afternoon - I was able to run draksetup postinstall without any issues and access localhost:6300 through Firefox. When I upload a sample and press analyze, drakvuf runs for a couple seconds and returns the below error message in the log.

> analysis UID: d3cdfe82-9c28-4da3-bfd9-c0e669ffefac
Running file as exe
Using file name ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa.exe
Running VM 1
running monitor 1
Copying sample to VM...
Something went wrong with the VM 1
Running VM 1
running monitor 1
Copying sample to VM...
Something went wrong with the VM 1
Running VM 1
running monitor 1
Copying sample to VM...
Something went wrong with the VM 1
Failed to analyze sample after 3 retries, giving up.

Any insight on this issue would be greatly appreciated. I've tried tinkering around for the last couple hours including changing file names, trying different samples, and rebooting without any luck.

Is there anything that I might be doing incorrectly?

Thanks,
Kyle

**Comment by icedevml** [comment]
```
VMI_ERROR: xen_start_single_step error: no system support for event type
Jan 20 14:49:10 ccre drakrun[494]: Failed to register singlestep for vCPU 0
Jan 20 14:49:10 ccre drakrun[494]: VMI_ERROR: xc_altp2m_switch_to_view returned rc: -1
Jan 20 14:49:10 ccre drakrun[494]: Failed to initialize on domain vm-1
```

You seem to be missing required hardware features.

**Comment by BonusPlay** [comment]
Long explanation: `xc_altp2m_switch_to_view` it a method to use altp2m which you can read about [here](https://xenproject.org/2016/04/13/stealthy-monitoring-with-xen-altp2m/). This is one of core features of DRAKVUF project and if it isn't supported on VMware Fusion then sadly DRAKVUF Sandbox also won't run :(

As for now, we don't see a way to "hack around" this issue as we did with previous ones. Thank you for helping us test DRAKVUF Sandbox on new platform, we hope that maybe in new versions of VMware Fusion maybe it will work. For now we can only recommend switching to VMware Workstation or bare-metal.

**Comment by MurbieDev** [comment]
I completely understand. Thank you for all of your help. I learned a lot and will look into purchasing a Windows machine that supports VMware Workstation to be able to run DRAKVUF. You may be hearing from me soon if I run into any issues running it on that end. :-)

Have a wonderful rest of the week!

**Comment by chivay** [comment]
> purchasing a Windows machine that supports VMware Workstation

If you have hardware to spare it's best to skip additional layer of virtualization and run Xen directly on your hardware (it's least likely to break and will have less overhead).

Thanks for testing the sandbox on a Macbook :+1:

**Comment by MurbieDev** [comment]
I ran BootCamp on the MacBook Pro Laptop and installed Windows 10. Running VMware Workstation Pro resolved the errors that I was getting and I am able to run analysis on malware samples now.

Thanks again!!
