### ISSUE TITLE
Out of memory in draksetup

### ISSUE THREAD

**Issue by manorit2001** [CERT-Polska/drakvuf-sandbox#449]
**Describe the bug**
```
Parsing config from /etc/drakrun/configs/vm-0.cfg
xc: error: panic: xc_dom_boot.c:122: xc_dom_boot_mem_init: can't allocate low memory for domain: Out of memory
libxl: error: libxl_dom.c:593:libxl__build_dom: xc_dom_boot_mem_init failed: Cannot allocate memory
libxl: error: libxl_create.c:1576:domcreate_rebuild_done: Domain 1:cannot (re-)build domain: -3
libxl: error: libxl_domain.c:1182:libxl__destroy_domid: Domain 1:Non-existant domain
libxl: error: libxl_domain.c:1136:domain_destroy_callback: Domain 1:Unable to destroy guest
libxl: error: libxl_domain.c:1063:domain_destroy_cb: Domain 1:Destruction of domain failed
```

**How to reproduce**

1. Install drakcore and drakrun on vmware debian buster machine
2. Configurations of the VM
- 5172MB ram
- 1 processor, 8 cores
- xfce DE is installed in the VM
2. Execute `draksetup install winall.iso`

**Comment by manorit2001** [comment]
Looking at `/etc/drakrun/configs/vm-0.cfg`
```
arch = 'x86_64'
name = "vm-0"
maxmem = 3048
memory = 3048
...
```

and, using `xl list`
```
user@debian:~$ sudo xl list
Name                                        ID   Mem VCPUs      State   Time(s)
Domain-0                                     0  2585     4     r-----    1426.9
```
It seems that the total memory required for the debian buster VM should be atleast more than 5.5GB

**Comment by icedevml** [comment]
Hello,

please check `/etc/drakrun/scripts/cfg.template`. You will have two memory-related keys there: `maxmem` and `memory`. Please edit these to `2048` and try again with the draksetup.

A different option would be to give a little bit more RAM to your Debian Buster VM (+1 GB?), looks like the minimal requirements are too optimistic.

**Comment by manorit2001** [comment]
Yeah sure, I will increase the ram for the VM. Just thought maybe an update to minimal ram requirements in the docs might help others also.
