### ISSUE TITLE
Checkpoints during the draksetup

### ISSUE THREAD

**Issue by manorit2001** [CERT-Polska/drakvuf-sandbox#454]
**Is your feature request related to a problem? Please describe.**
The installation of the iso is a time consuming process. 
During the sandbox setup, After installing the iso through `draksetup install`, I had issued `draksetup postinstall` and for some development changes, I had interrupted the command which caused some errors as mentioned in #451 . 
The whole installation process was rendered useless due to that and I had to go again for installation of the iso from beginning. 

**Describe the solution you'd like**
- It would actually be nice if some backup is created initially after `draksetup install` which can be used later by invoking some other `draksetup command` for example `draksetup reset <iso>` if same iso is being installed next time(by identifying the hashes) which will reset the state of the installation similar to the state after `draksetup install`
- This change will also help the users using the tool in situations where some unforeseen error has occurred and they need to do the restore the installed initial configuration again

**Comment by icedevml** [comment]
Hi, I would rather want to keep install/postinstall process as simple as possible. It's already very complicated and this `reset` command would be yet another thing to test.

**Comment by manorit2001** [comment]
> Hi, I would rather want to keep install/postinstall process as simple as possible. It's already very complicated and this `reset` command would be yet another thing to test.
>
> So generally I'm against this :(

Makes sense, even I wouldn't want to complicate the already complicated part which might introduce more errors. 

Any other possible solution you have in mind apart from this then?

**Comment by icedevml** [comment]
I wrote in #451 that we should account for the cases when some resource is leaked and make a proper clean up in the second run of `draksetup`.

**Comment by manorit2001** [comment]
> I wrote in #451 that we should account for the cases when some resource is leaked and make a proper clean up in the second run of `draksetup`.

This sounds nice, it will help remove the manual work of the cleanup atleast in case of reinstallations.
