### ISSUE TITLE
Serve packages through APT repository

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/drakvuf-sandbox#5]
We should setup a custom simple package repository to make distribution and installation easier.

**Comment by icedevml** [comment]
Right now `drakvuf-bundle` is not suitable for hosting in PPA because the versioning scheme is incompatible with Debian.

PR to DRAKVUF was sent to address that: https://github.com/tklengyel/drakvuf/pull/860

**Comment by psrok1** [comment]
No longer planned, DRAKVUF Sandbox becomes a Python package as it's just a toolkit around DRAKVUF.
