### ISSUE TITLE
Provide default syscall filter in /etc/drakrun

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/drakvuf-sandbox#54]
Fix this leftover in code:
https://github.com/CERT-Polska/drakvuf-sandbox/blob/9fad1a93c072fa3e0502b318ecca30782031c04a/drakrun/drakrun/main.py#L337

**Comment by icedevml** [comment]
For the latest DRAKVUF version, drakrun postprocessing is not able to parse syscalls logs due to a bug.

External PR: https://github.com/tklengyel/drakvuf/pull/861

**Comment by icedevml** [comment]
:thinking: actually after testing it turns out that the syscall filter is not required, JSON parsing errors were slowing down the process a lot, but now these are fixed and it seems to run fine

**Comment by BonusPlay** [comment]
Does that mean we can close this issue, or we still want a default filter?

**Comment by icedevml** [comment]
@BonusPlay It's not critical anymore but we do want the feature. I bet there should be something like `/etc/drakrun/syscalls.txt` to configure the syscalls filter and also some switch in `config.ini` whether to enable filtering or not.
