### ISSUE TITLE
slack channel invite

### ISSUE THREAD

**Issue by manorit2001** [CERT-Polska/drakvuf-sandbox#541]
**What would you like to ask us?**

Right now, the slack channel given in readme is of `kvm-vmi`.
  <a href="https://kvm-vmi.slack.com">
    <img src="https://img.shields.io/badge/Slack-KVM--VMI-important" alt="Slack">
  </a>
And, the url which is given is not some invite link to the slack, the invite link seems to be different i.e 
<a href="https://kvm-vmi.herokuapp.com">
    <img src="https://img.shields.io/badge/Slack-Join%20KVM--VMI-blue">
  <a>
If the supported slack channel of drakvuf-sandbox is `kvm-vmi` only, then it would make sense to add the joining link also here

**Comment by chivay** [comment]
It's a good idea, but i'm not sure if we should keep both of them or maybe only a "join" badge

**Comment by manorit2001** [comment]
> It's a good idea, but i'm not sure if we should keep both of them or maybe only a "join" badge

[kvm-vmi](https://github.com/KVM-VMI/kvm-vmi) repo keeps them both if it helps

**Comment by chivay** [comment]
OK, I guess we can keep both of them. @manorit2001 could you submit a PR with this change?
