### ISSUE TITLE
drakvuf-bundle: Provide some good defaults for dom0 vcpu amount and dom0 memory

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/drakvuf-sandbox#57]
https://github.com/tklengyel/drakvuf/blob/master/package/extra/etc/default/grub.d/xen.cfg

Probably half CPUs and half RAM to Dom0 by default?

Plus warning if the current configuration doesn't allow to run any virtual machine (total ram < dom0_ram + single_vm_ram).

**Comment by icedevml** [comment]
Without Xen:
```
CPU=$(nproc --all)
RAM=$(($(getconf _PHYS_PAGES) * $(getconf PAGE_SIZE) / (1024 * 1024)))
```

with Xen:
```
CPU=$(xl info | grep nr_cpus | cut -f2 '-d:' | xargs)
RAM=$(xl info | grep total_memory | cut -f2 '-d:' | xargs)
```

then
```
# (CPU < 2) => error

VM_MEM=$(cat /etc/drakrun/scripts/cfg.template | grep maxmem | cut -f2 -d= | xargs)
# (RAM_H < VM_MEM + 256 MB reserve) => error

CPU_H=$(expr "$CPU" / 2)
RAM_H=$(expr "$RAM" / 2)
```

**Comment by icedevml** [comment]
@tklengyel I'm thinking about good defaults for drakvuf-bundle Xen command line.

Currently it's fixed to 4 cores and 2048 MB for Dom0:
https://github.com/tklengyel/drakvuf/blob/7b97faeaed1b96a9d0f5c5bc3767572df85f0a05/package/extra/etc/default/grub.d/xen.cfg#L16

do you think that reserving half of RAM and CPU by default to Dom0 is a good idea? This is not the best proportion ever but I think would work well for anything that has >= 2 cores and >=4 GB RAM.

**Comment by tklengyel** [comment]
Really depends on the system spec. If its a 4 cpu 16gb machine then 2 vcpu 4gb dom0 sounds fine. If you have more cores and you want to run more VMs monitored then its not going to cut it, I might even recommend pinning some cores to dom0 so that it can process all the incoming events.

**Comment by icedevml** [comment]
related PR https://github.com/tklengyel/drakvuf/pull/864

**Comment by icedevml** [comment]
upstream merged

**Comment by tklengyel** [comment]
Actually it might be worth investigating whether dom0_vcpus_pin is a good option to have or not. While it keeps the dom0 vcpus on the same pcpus and thus theoretically can help with keeping the caches hot, if the system is overloaded with incoming events dom0 mat not be allowed to be scheduled to run on a cpu that just trapped to send an event.

**Comment by icedevml** [comment]
By our experience, looks like having CPUs unpinned is causing some weird bugs (e.g. host system freeze), but only if some extra (yet unknown) conditions are met.

**Comment by icedevml** [comment]
> if the system is overloaded with incoming events dom0 may not be allowed to be scheduled to run on a cpu that just trapped to send an event

Hm. This may be the case. Sometimes there is something that looks like a complete deadlock.

**Comment by tklengyel** [comment]
I'm not talking about a complete deadlock above, just that dom0 needs to wait till its pinned pcpus become available again. A deadlock would be a very different issue.

**Comment by icedevml** [comment]
> I'm not talking about a complete deadlock above, just that dom0 needs to wait till its pinned pcpus become available again. A deadlock would be a very different issue.

Okay, thanks for clarification. I previously thought it was related.

Closing because the actual defaults are now provided in drakvuf-bundle.
