### ISSUE TITLE
Question/Bug: is encrypted traffic saved to the dump.pcap file troughout the analysis?

### ISSUE THREAD

**Issue by Latanyor** [CERT-Polska/drakvuf-sandbox#590]
I am currently trying and testing the new TLS Key extraction feature of the sandbox and have some issues getting good results.

After several samples and their analysis in the sandbox I have found some which acctually make use of encyrption. But in the network dump I can only see a handshake beeing made and directly afterwards the connection is closed. 

See these examples:

![tls_handshake_closed](https://user-images.githubusercontent.com/35563666/125260614-ccc68700-e300-11eb-8368-5ebb99800328.png)

![hunderes_of_requests](https://user-images.githubusercontent.com/35563666/125260598-c89a6980-e300-11eb-9b4b-a795c8b7b8b8.png)

I have observed this behavior on several different samples.

------

Is this a weird behavior of my samples, am I missing something or does the sandbox not save encrypted traffic at all?

**Comment by chivay** [comment]
Hi,
when capturing network traffic, there's no distinction between encrypted/non-encrypted data.
Everything that appeared on the interface is saved to pcap file.

It seems to me that in both cases TLS session either isn't fully established or no data is sent.
Are you sure that those samples are working correctly?

**Comment by Latanyor** [comment]
Thanks!

I'm not 100 percent sure but i've tested a dozen samples by now and all of them show the same behavior. 
Will look further into that.
