### ISSUE TITLE
Problem with VM - run less 1 minute

### ISSUE THREAD

**Issue by artv2007** [CERT-Polska/drakvuf-sandbox#611]
**Describe the bug**

We have problems with getting normal results of the virtual machine.
According to the information from the logs, we see that after loading the sample, the VM starts, the sample is loaded into it, and run, IP address is received. But after that, tcpdump is launched, statistics on network packets are generated and bridge interfaces are down. 
All this happens in less than the time allotted for VM working.

We get the analysis results, but there no information about sample working...

in logs we see a lot of
Aug 11 13:12:59 madoka drakrun[16312]: Critical error in removing int3

and after that
Aug 11 13:12:59 madoka drakrun[16312]: VMI_ERROR: xen_events_destroy error: couldn't disable monitor vm_event ring.
Aug 11 13:12:59 madoka drakrun[16305]: dnsmasq: exiting on receipt of SIGTERM
Aug 11 13:12:59 madoka dnsmasq[16305]: exiting on receipt of SIGTERM

**How to reproduce**

1. Install drakcore and drakrun
2. Execute `sudo draksetup install --memory 4096 --vcpus 4 win7-sp1-2011.iso`
3. Install additional software like Office, VC++ components, browser, adobe and so on
4. Execute 'sudo draksetup postinstall --no-report'
5. Submit sample by Web UI or by MWDB

**Output of the [status checking commands](https://github.com/CERT-Polska/drakvuf-sandbox#checking-service-status)**

drak-healthcheck
Checking daemon status...
drak-web.service              OK
drak-system.service           ERROR (i think its normal because we have system_disable=1 in config and separate server with karton)
drak-minio.service            OK
Checking worker status...
drakrun@1.service             OK
drak-postprocess@1.service    OK

journalctl -e -u drakrun@1

```
Aug 11 09:38:50 madoka drakrun[14687]: [2021-08-11 09:38:50,592][INFO] Gracefully shutting down!
Aug 11 09:38:50 madoka drakrun[14687]: INFO:karton.drakrun-prod:Gracefully shutting down!
Aug 11 09:38:55 madoka systemd[1]: drakrun@1.service: Succeeded.
Aug 11 09:38:55 madoka systemd[1]: Stopped drakrun service.
Aug 11 10:12:28 madoka systemd[1]: Started drakrun service.
Aug 11 10:12:28 madoka drakrun[15736]: [2021-08-11 10:12:28,703][INFO] Generated VM configuration for vm-1
Aug 11 10:12:28 madoka drakrun[15736]: [2021-08-11 10:12:28,723][INFO] Bridge drak1 already exists.
Aug 11 10:12:28 madoka drakrun[15736]: [2021-08-11 10:12:28,793][INFO] Service karton.drakrun-prod started
Aug 11 10:12:28 madoka drakrun[15736]: INFO:karton.drakrun-prod:Service karton.drakrun-prod started
Aug 11 10:12:28 madoka drakrun[15736]: [2021-08-11 10:12:28,796][INFO] Binding on: {'type': 'sample', 'stage': 'recognized', 'platform': 'win32'}
Aug 11 10:12:28 madoka drakrun[15736]: INFO:karton.drakrun-prod:Binding on: {'type': 'sample', 'stage': 'recognized', 'platform': 'win32'}
Aug 11 10:12:28 madoka drakrun[15736]: [2021-08-11 10:12:28,797][INFO] Binding on: {'type': 'sample', 'stage': 'recognized', 'platform': 'win64'}
Aug 11 10:12:28 madoka drakrun[15736]: INFO:karton.drakrun-prod:Binding on: {'type': 'sample', 'stage': 'recognized', 'platform': 'win64'}
Aug 11 13:07:52 madoka drakrun[15736]: [2021-08-11 13:07:52,082][INFO] Received new task - 9952deea-6ed2-4b60-8f86-b7c9f82c2bdb
Aug 11 13:07:52 madoka drakrun[15736]: INFO:karton.drakrun-prod:Received new task - 9952deea-6ed2-4b60-8f86-b7c9f82c2bdb
Aug 11 13:07:52 madoka drakrun[15736]: [2021-08-11 13:07:52,094][INFO] Running on: madoka
Aug 11 13:07:52 madoka drakrun[15736]: INFO:karton.drakrun-prod:Running on: madoka
Aug 11 13:07:52 madoka drakrun[15736]: [2021-08-11 13:07:52,095][INFO] Sample SHA256: ecf73b44ea6651c582349d5b359edd76a1160bffa43d9e090f8f0858e82f5fca
Aug 11 13:07:52 madoka drakrun[15736]: INFO:karton.drakrun-prod:Sample SHA256: ecf73b44ea6651c582349d5b359edd76a1160bffa43d9e090f8f0858e82f5fca
Aug 11 13:07:52 madoka drakrun[15736]: [2021-08-11 13:07:52,096][INFO] Analysis UID: 9952deea-6ed2-4b60-8f86-b7c9f82c2bdb
Aug 11 13:07:52 madoka drakrun[15736]: INFO:karton.drakrun-prod:Analysis UID: 9952deea-6ed2-4b60-8f86-b7c9f82c2bdb
Aug 11 13:07:52 madoka drakrun[15736]: [2021-08-11 13:07:52,097][INFO] Running file as doc
Aug 11 13:07:52 madoka drakrun[15736]: INFO:karton.drakrun-prod:Running file as doc
Aug 11 13:07:52 madoka drakrun[15736]: [2021-08-11 13:07:52,098][INFO] Using file name malwar.doc
Aug 11 13:07:52 madoka drakrun[15736]: INFO:karton.drakrun-prod:Using file name malwar.doc
Aug 11 13:07:52 madoka drakrun[15736]: [2021-08-11 13:07:52,126][INFO] Start command: cmd.exe /C start winword.exe /t %f /mAuto_Open
Aug 11 13:07:52 madoka drakrun[15736]: INFO:karton.drakrun-prod:Start command: cmd.exe /C start winword.exe /t %f /mAuto_Open
Aug 11 13:07:52 madoka drakrun[15736]: [2021-08-11 13:07:52,127][INFO] Trying to analyze sample (attempt 1/3)
Aug 11 13:07:52 madoka drakrun[15736]: INFO:karton.drakrun-prod:Trying to analyze sample (attempt 1/3)
Aug 11 13:07:52 madoka drakrun[16160]: Formatting '/var/lib/drakrun/volumes/vm-1.img', fmt=qcow2 size=107374182400 backing_file=/var/lib/drakrun/volumes/vm-0.img backing_fmt=qcow2 cluster_size=65536 lazy_refcounts=off refcount_bits=16
Aug 11 13:07:52 madoka drakrun[16163]: Loading new save file /var/lib/drakrun/volumes/snapshot.sav (new xl fmt info 0x3/0x0/2063)
Aug 11 13:07:52 madoka drakrun[16163]:  Savefile contains xl domain config in JSON format
Aug 11 13:07:52 madoka drakrun[16163]: Parsing config from /etc/drakrun/configs/vm-1.cfg
Aug 11 13:07:52 madoka drakrun[16163]: xc: info: Found x86 HVM domain from Xen 4.15
Aug 11 13:07:52 madoka drakrun[16163]: xc: info: Restoring domain
Aug 11 13:07:57 madoka drakrun[16163]: xc: info: Restore successful
Aug 11 13:07:57 madoka drakrun[16163]: xc: info: XenStore: mfn 0xfeffc, dom 0, evt 1
Aug 11 13:07:57 madoka drakrun[16163]: xc: info: Console: mfn 0xfefff, dom 0, evt 2
Aug 11 13:07:58 madoka root[16207]: /etc/xen/scripts/vif-bridge: online type_if=vif XENBUS_PATH=backend/vif/33/0
Aug 11 13:07:58 madoka root[16234]: /etc/xen/scripts/vif-bridge: drak1 MTU is 1500
Aug 11 13:07:58 madoka root[16235]: /etc/xen/scripts/vif-bridge: setting vif33.0 MTU to 1500
Aug 11 13:07:58 madoka root[16237]: /etc/xen/scripts/vif-bridge: Writing /local/domain/33/device/vif/0/mtu 1500 to xenstore.
Aug 11 13:07:58 madoka root[16239]: /etc/xen/scripts/vif-bridge: adding vif33.0 to bridge drak1
Aug 11 13:07:58 madoka root[16253]: /etc/xen/scripts/vif-bridge: Writing backend/vif/33/0/hotplug-status connected to xenstore.
Aug 11 13:07:58 madoka root[16263]: /etc/xen/scripts/vif-bridge: add type_if=tap XENBUS_PATH=backend/vif/33/0
Aug 11 13:07:58 madoka root[16286]: /etc/xen/scripts/vif-bridge: adding vif33.0-emu to bridge drak1
Aug 11 13:07:58 madoka root[16299]: /etc/xen/scripts/vif-bridge: Successful vif-bridge add for vif33.0-emu, bridge drak1.
Aug 11 13:07:58 madoka drakrun[15736]: [2021-08-11 13:07:58,354][INFO] VM restored
Aug 11 13:07:58 madoka drakrun[15736]: INFO:karton.drakrun-prod:VM restored
Aug 11 13:07:58 madoka drakrun[16305]: dnsmasq: started, version 2.80 DNS disabled
Aug 11 13:07:58 madoka drakrun[16305]: dnsmasq: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth nettlehash DNSSEC loop-detect inotify dumpfile
Aug 11 13:07:58 madoka drakrun[16305]: dnsmasq-dhcp: DHCP, IP range 10.13.1.100 -- 10.13.1.200, lease time 12h
Aug 11 13:07:58 madoka drakrun[16305]: dnsmasq-dhcp: DHCP, sockets bound exclusively to interface drak1
Aug 11 13:07:58 madoka dnsmasq[16305]: started, version 2.80 DNS disabled
Aug 11 13:07:58 madoka dnsmasq[16305]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth nettlehash DNSSEC loop-detect inotify dumpfile
Aug 11 13:07:58 madoka dnsmasq-dhcp[16305]: DHCP, IP range 10.13.1.100 -- 10.13.1.200, lease time 12h
Aug 11 13:07:58 madoka dnsmasq-dhcp[16305]: DHCP, sockets bound exclusively to interface drak1
Aug 11 13:07:58 madoka drakrun[16308]: tcpdump version 4.9.3
Aug 11 13:07:58 madoka drakrun[16308]: libpcap version 1.9.1 (with TPACKET_V3)
Aug 11 13:07:58 madoka drakrun[16308]: OpenSSL 1.1.1f  31 Mar 2020
Aug 11 13:07:58 madoka drakrun[15736]: [2021-08-11 13:07:58,416][INFO] Copying sample to VM...
Aug 11 13:07:58 madoka drakrun[15736]: INFO:karton.drakrun-prod:Copying sample to VM...
Aug 11 13:07:58 madoka drakrun[16310]: DRAKVUF injector v0.8-git20210714133600+095a35f-1 Copyright (C) 2014-2021 Tamas K Lengyel
Aug 11 13:07:58 madoka drakrun[16309]: tcpdump: listening on vif33.0-emu, link-type EN10MB (Ethernet), capture size 262144 bytes
Aug 11 13:07:58 madoka drakrun[15736]: [2021-08-11 13:07:58,559][INFO] Using command: cmd.exe /C start winword.exe /t C:\Users\user\Desktop\malwar.doc /mAuto_Open
Aug 11 13:07:58 madoka drakrun[15736]: INFO:karton.drakrun-prod:Using command: cmd.exe /C start winword.exe /t C:\Users\user\Desktop\malwar.doc /mAuto_Open
Aug 11 13:07:58 madoka drakrun[15736]: [2021-08-11 13:07:58,562][INFO] Setting up network...
Aug 11 13:07:58 madoka drakrun[15736]: INFO:karton.drakrun-prod:Setting up network...
Aug 11 13:07:58 madoka drakrun[16311]: DRAKVUF injector v0.8-git20210714133600+095a35f-1 Copyright (C) 2014-2021 Tamas K Lengyel
Aug 11 13:07:58 madoka drakrun[16305]: dnsmasq-dhcp: DHCPREQUEST(drak1) 10.13.0.193 00:16:3e:66:65:62
Aug 11 13:07:58 madoka drakrun[16305]: dnsmasq-dhcp: DHCPNAK(drak1) 10.13.0.193 00:16:3e:66:65:62 lease not found
Aug 11 13:07:58 madoka dnsmasq-dhcp[16305]: DHCPREQUEST(drak1) 10.13.0.193 00:16:3e:66:65:62
Aug 11 13:07:58 madoka dnsmasq-dhcp[16305]: DHCPNAK(drak1) 10.13.0.193 00:16:3e:66:65:62 lease not found
Aug 11 13:07:58 madoka drakrun[16311]: {"Plugin": "inject", "TimeStamp": "1628687278.914954", "Status": "Success", "ProcessName": "", "Arguments": "/C ipconfig /renew >nul", "InjectedPid": 3224, "InjectedTid": 3252}
Aug 11 13:07:58 madoka drakrun[16312]: 1628687278.956010 DRAKVUF v0.8-git20210714133600+095a35f-1 Copyright (C) 2014-2021 Tamas K Lengyel
Aug 11 13:08:00 madoka drakrun[16309]: tcpdump: pcap_loop: The interface went down
Aug 11 13:08:00 madoka drakrun[16309]: 33 packets captured
Aug 11 13:08:00 madoka drakrun[16309]: 33 packets received by filter
Aug 11 13:08:00 madoka drakrun[16309]: 0 packets dropped by kernel
Aug 11 13:08:00 madoka root[16324]: /etc/xen/scripts/vif-bridge: offline type_if=vif XENBUS_PATH=backend/vif/33/0
Aug 11 13:08:00 madoka root[16341]: /etc/xen/scripts/vif-bridge: ip link set dev vif33.0 down failed
Aug 11 13:08:00 madoka root[16342]: /etc/xen/scripts/vif-bridge: vif33.0 not on bridge drak1
Aug 11 13:08:00 madoka root[16352]: /etc/xen/scripts/vif-bridge: Successful vif-bridge offline for vif33.0, bridge drak1.
Aug 11 13:08:00 madoka root[16361]: /etc/xen/scripts/vif-bridge: remove type_if=tap XENBUS_PATH=backend/vif/33/0
Aug 11 13:08:00 madoka root[16376]: /etc/xen/scripts/vif-bridge: ip link set dev vif33.0-emu down failed
Aug 11 13:08:00 madoka root[16377]: /etc/xen/scripts/vif-bridge: vif33.0-emu not on bridge drak1
Aug 11 13:08:01 madoka drakrun[16305]: dnsmasq-dhcp: DHCPDISCOVER(drak1) 00:16:3e:66:65:62
Aug 11 13:08:01 madoka drakrun[16305]: dnsmasq-dhcp: DHCPOFFER(drak1) 10.13.1.193 00:16:3e:66:65:62
Aug 11 13:08:01 madoka dnsmasq-dhcp[16305]: DHCPDISCOVER(drak1) 00:16:3e:66:65:62
Aug 11 13:08:01 madoka dnsmasq-dhcp[16305]: DHCPOFFER(drak1) 10.13.1.193 00:16:3e:66:65:62
Aug 11 13:12:59 madoka drakrun[16312]: Critical error in removing int3
Aug 11 13:12:59 madoka drakrun[16312]: Critical error in removing int3
Aug 11 13:12:59 madoka drakrun[16312]: Critical error in removing int3
... a lot of error
Aug 11 13:12:59 madoka drakrun[16312]: Critical error in removing int3
Aug 11 13:12:59 madoka drakrun[16312]: Critical error in removing int3
Aug 11 13:12:59 madoka drakrun[16312]: Critical error in removing int3
Aug 11 13:12:59 madoka drakrun[16312]: VMI_ERROR: xen_events_destroy error: couldn't disable monitor vm_event ring.
Aug 11 13:12:59 madoka drakrun[16305]: dnsmasq: exiting on receipt of SIGTERM
Aug 11 13:12:59 madoka dnsmasq[16305]: exiting on receipt of SIGTERM
Aug 11 13:12:59 madoka drakrun[15736]: [2021-08-11 13:12:59,540][INFO] Analysis done. Collecting artifacts...
Aug 11 13:12:59 madoka drakrun[15736]: INFO:karton.drakrun-prod:Analysis done. Collecting artifacts...
Aug 11 13:12:59 madoka drakrun[15736]: [2021-08-11 13:12:59,545][INFO] Uploading artifacts...
Aug 11 13:12:59 madoka drakrun[15736]: INFO:karton.drakrun-prod:Uploading artifacts...
Aug 11 13:13:00 madoka drakrun[15736]: [2021-08-11 13:13:00,165][INFO] Task done - 9952deea-6ed2-4b60-8f86-b7c9f82c2bdb
Aug 11 13:13:00 madoka drakrun[15736]: INFO:karton.drakrun-prod:Task done - 9952deea-6ed2-4b60-8f86-b7c9f82c2bdb
```

[output_log.txt](https://github.com/CERT-Polska/drakvuf-sandbox/files/6969287/output_log.txt)

**Comment by BonusPlay** [comment]
We have recently bumped into a very similar issue, glad to confirm that we're not the only one. Could you provide info about your setup (lscpu, uname -a, etc.)?

**Comment by artv2007** [comment]
HP DL 360

lscpu

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   40 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              8
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           44
Model name:                      Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz
Stepping:                        2
CPU MHz:                         3066.792
BogoMIPS:                        6133.59
Hypervisor vendor:               Xen
Virtualization type:             none
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        256 KiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Unknown (XEN PV detected, hypervisor mitigation required)
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid tsc_known_freq pni pclmulqdq est ssse3 cx16
                                  sse4_1 sse4_2 popcnt aes hypervisor lahf_lm

uname -a
Linux madoka 5.10.0-1038-oem #40-Ubuntu SMP Fri Jul 16 15:08:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"

drakcore/now 0.16.0 amd64 [installed,local]
drakrun/now 0.16.0 amd64 [installed,local]
drakvuf-bundle/now 0.8-git20210714133600+095a35f-1 amd64 [installed,local]

sudo xl info
host                   : madoka
release                : 5.10.0-1038-oem
version                : #40-Ubuntu SMP Fri Jul 16 15:08:30 UTC 2021
machine                : x86_64
nr_cpus                : 12
max_cpu_id             : 31
nr_nodes               : 2
cores_per_socket       : 6
threads_per_core       : 1
cpu_mhz                : 3066.797
hw_caps                : bfebfbff:029ee3ff:2c100800:00000001:00000000:00000000:00000000:00000100
virt_caps              : pv hvm hap shadow
total_memory           : 147445
free_memory            : 129467
sharing_freed_memory   : 0
sharing_used_memory    : 0
outstanding_claims     : 0
free_cpus              : 0
xen_major              : 4
xen_minor              : 15
xen_extra              : .0
xen_version            : 4.15.0
xen_caps               : xen-3.0-x86_64 xen-3.0-x86_32p hvm-3.0-x86_32 hvm-3.0-x86_32p hvm-3.0-x86_64 
xen_scheduler          : credit
xen_pagesize           : 4096
platform_params        : virt_start=0xffff800000000000
xen_changeset          : 
xen_commandline        : placeholder dom0_mem=16384M,max:16384M dom0_max_vcpus=8 dom0_vcpus_pin=1 force-ept=1 ept=pml=0 hap_1gb=0 hap_2mb=0 altp2m=1 hpet=legacy-replacement smt=0 sched=credit
cc_compiler            : gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
cc_compile_by          : root
cc_compile_domain      : 
cc_compile_date        : Mon Aug  2 22:10:41 UTC 2021
build_id               : 6149dce47f949927cdcacdf86e8dad12382eea1d
xend_config_format     : 4

**Comment by artv2007** [comment]
Maybe there is a workaround? 
Maybe an older version? 
Do you have any ideas why this could be? 
We tried another hardware, but the result is the same. 
Any suggestions?

**Comment by psrok1** [comment]
Issue is stale and looks like a problem with Drakvuf engine. VM is crashing and I guess it's due to Windows BSoD. In the same time, Drakvuf is more developed than in 2021 and probably some bugs are already fixed.

If you run into troubles with the current version, feel free to create a new issue.
