### ISSUE TITLE
Routing HTTPS over proxy

### ISSUE THREAD

**Issue by kaboreka** [CERT-Polska/drakvuf-sandbox#622]
Hi
How can we route vm https traffic over proxy? I tried with mitmproxy (https://docs.mitmproxy.org/stable/howto-transparent-vms/) but i cant route. 
Is there any plan to support https inspection?

**Comment by chivay** [comment]
Hi,
If your goal is to decrypt HTTPS traffic, we've already got support for that via `tlsmon` plugin that dumps crypto keys in Wireshark format.
Live request interception/modification during analysis is currently of of scope.

However if you'd like to experiment with it, you should be able to do this by adding appropriate iptables rules, similarly to
https://docs.mitmproxy.org/stable/howto-transparent-vms/#3-redirect-traffic-to-mitmproxy
