### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by chivay** [CERT-Polska/drakvuf-sandbox#623]
- [ ] DRAKVUF
    - [x] https://github.com/tklengyel/drakvuf/pull/1288
    - [x] https://github.com/tklengyel/drakvuf/pull/1284
    - [x] https://github.com/tklengyel/drakvuf/pull/1300
- [ ] draksetup
- [ ] profiles
- [ ] drakrun
- [ ] postprocessing

**Comment by manorit2001** [comment]
Hi, `execve` method is also merged. You can update that list

**Comment by chivay** [comment]
Updated. Thanks

**Comment by psrok1** [comment]
Right now we don't have interest in supporting Linux and current Drakvuf Sandbox codebase is too strongly pinned to Windows in various places.

Of course we're open for contributions and I hope that proper Linux guest support will be much easier to implement in the future.
