### ISSUE TITLE
x86 Support?

### ISSUE THREAD

**Issue by lazydaemon** [CERT-Polska/drakvuf-sandbox#634]
Hey guys, did you just not mention it or is x86 not supported? If its not supported, do you have any plans to support it in future? Thanks

**Comment by chivay** [comment]
Hi,
32 bit versions of Windows are not officially supported (since we're not using them internally),
however they should work at least partially.
AFAIK, not all of drakvuf's plugins are ported and tested on x86, so you may experience some bugs.

**Comment by lazydaemon** [comment]
Ok, thanks.
