### ISSUE TITLE
No artifacts uploaded

### ISSUE THREAD

**Issue by 4rchib4ld** [CERT-Polska/drakvuf-sandbox#665]
**Describe the bug**

Once connected to an external Karton instance, Drakvuf sandbox doesn't upload artifacts to the MWDB instance.
There is no mention of an ongoing (or failed) task nowhere on the dashboard.

**How to reproduce**

1. Basic MWDB install
2. Basic Drakvuf install
3. Upload a sample to MWDB

Content of post-process :
```{"levelname": "INFO", "created": 1635521515.2634943, "message": "Skipping generate_wireshark_key_file, missing resources"}```

Content of drakrun : 
```
{"levelname": "INFO", "created": 1635520810.88331, "message": "Running on: ubuntu"}
{"levelname": "INFO", "created": 1635520810.883899, "message": "Sample SHA256: 0a0b3d91698a46d409791d4dd866e56ddd70f91a3f1d4557a0cb2899bda1e524"}
{"levelname": "INFO", "created": 1635520810.8844457, "message": "Analysis UID: 27312080-5437-48e4-9e56-7f6a1647e287"}
{"levelname": "INFO", "created": 1635520810.884792, "message": "Snapshot SHA256: c57148ec9f0f63c87a04ff036aee35b51aff3f8c667e939902656795930fa612"}
{"levelname": "INFO", "created": 1635520810.8852847, "message": "Running file as dll"}
{"levelname": "INFO", "created": 1635520810.8859222, "message": "Using file name malwar.dll"}
{"levelname": "INFO", "created": 1635520810.8926737, "message": "Trying to analyze sample (attempt 1/3)"}
{"levelname": "INFO", "created": 1635520816.5869467, "message": "VM restored"}
{"levelname": "INFO", "created": 1635520816.6545835, "message": "Copying sample to VM..."}
{"levelname": "INFO", "created": 1635520817.6696913, "message": "Using command: regsvr32 /s C:\\Users\\root\\Desktop\\malwar.dll"}
{"levelname": "INFO", "created": 1635521421.4789116, "message": "Analysis done. Collecting artifacts..."}
{"levelname": "INFO", "created": 1635521421.9422967, "message": "Uploading artifacts..."}
```

By checking `journalctl -e -u drak-postprocess@1` there is no mention of an upload, failed or not :

![Screenshot_20211029_180108](https://user-images.githubusercontent.com/65158158/139466872-1ccdfd59-b3d1-49d3-b29a-a1c11c549b30.png)

`journalctl -e -u drakrun@1` doesn't show any error : 

![Screenshot_20211029_182118](https://user-images.githubusercontent.com/65158158/139469674-8c5087c5-f8ae-460b-9122-bdffbfc2b6a3.png)

Other than that, everything runs smoothly !

**Comment by chivay** [comment]
Hi,
this is working as intended. DRAKVUF Sandbox doesn't upload analysis artifacts to MWDB instance by itself.
To do this you have to run additional karton services:
* config-extractor - https://github.com/CERT-Polska/karton-config-extractor - to unpack dumps.zip (and maybe extract configs) and send new tasks for each dump.
* mwdb-reporter https://github.com/CERT-Polska/karton-mwdb-reporter. - to push dumps to MWDB.

**Comment by 4rchib4ld** [comment]
Hi,
Thanks for your response ! I have this two services up and running. I used this [dockerfile](https://github.com/CERT-Polska/mwdb-core/blob/master/docker-compose-dev-karton.yml).

Does that means that I need to setup additional tasks ? I assumed that the dumps get uploaded without having to write a config extractor module  and then you can use yara (or anything else) on them in MWDB. Did I misunderstood the process ?

**Comment by chivay** [comment]
Unfortunately, current implementation of config-extractor doesn't allow uploading unripped dumps.
It was made this way to avoid inundating MWDB with useless dumps.

**Comment by 4rchib4ld** [comment]
Yeah, that's a good design. The message I got was just misleading (at least for me).

I understand more deeply the inner working of Karton/Drakvuf now.

I'm closing this issue, and thanks again for your amazing work !
