### ISSUE TITLE
windows 10 version 

### ISSUE THREAD

**Issue by Loky85** [CERT-Polska/drakvuf-sandbox#672]
Which version of windows 10 can be installed?, I tried the latest version, but when I run the draksetup postinstall command, I get various errors. Win 7 works well for me.

**Comment by Loky85** [comment]
And whether both operating systems Win7 and Win10 (vm-0, vm-1) can run in the background?or only one can be analyzed  example vm-0.

**Comment by BonusPlay** [comment]
vm-0 is used "under the hood" and isn't an actual VM can run samples on. If you want to run samples on both Win7 and Win10 you would need 2 separate drakvuf-sandbox instances. A feature for supporting multiple OSes in one drakvuf-sandbox instance is tracked here: https://github.com/CERT-Polska/drakvuf-sandbox/issues/462
