### ISSUE TITLE
Analysis of samples that require privilege elevation

### ISSUE THREAD

**Issue by Carlos-Borau** [CERT-Polska/drakvuf-sandbox#723]
I am currently using drakvuf sandbox v0.17.2 and was trying to analyze the behavior of a malware sample that modifies certain windows registry entries under HKLM, which requires admin privileges. As such this sample will prompt the user a window requesting admin privileges to be executed, so when installing the VM instance I disabled this messages, thus allowing samples with such behavior to be directly executed with admin privileges without the need to interact with a user.

This all seemed well to me, but when trying to analyze the sample the drakrun log showed the following error: "Injection failed with error: ERROR_ELEVATION_REQUIRED".

My questions would be the following: 
-Is it posible to analyze a malware sample that requires admin privileges to be executed with drakvuf sandbox? 
-If yes: How? 
-If no: Why?, Is it a feature planned to be added in the future?

Thx in advance.

**Comment by BonusPlay** [comment]
It can be done manually by using the vnc during analysis and manually running sample as admin, but that is only valid choice for "one-time" analysis. Currently drakvuf-sandbox has no feature like that to run a sample with admin privileges.
