### ISSUE TITLE
Injector quote arguments

### ISSUE THREAD

**Issue by BonusPlay** [CERT-Polska/drakvuf-sandbox#724]
atm if there's a space in path (like username) injector fails with
```
{"Plugin":"inject","TimeStamp":"1655392234.441550","Method":"CreateProc","Status":"Error","ErrorCode":267,"Error":"ERROR_DIRECTORY"}
```

**Comment by manorit2001** [comment]
> atm if there's a space in path (like username) injector fails with
> 
> ```
> {"Plugin":"inject","TimeStamp":"1655392234.441550","Method":"CreateProc","Status":"Error","ErrorCode":267,"Error":"ERROR_DIRECTORY"}
> ```

Is this a regression or was it there before too?

**Comment by psrok1** [comment]
It looks like `-e` argument is directly passed as lpCommandLine argument for CreateProcess WinAPI call. As it's a command-line, correct quoting makes a huge difference:

```python
In [5]: run(r"c:\program files\windows nt\accessories\wordpad.exe")
DRAKVUF injector v1.1-git20230901115228+3a0905b-1 Copyright (C) 2014-2023 Tamas K Lengyel
{"Plugin": "inject", "TimeStamp": "1707758697.328517", "Method": "CreateProc", "Status": "Success", "ProcessName": "c:\\program", "Arguments": "files\\windows nt\\accessories\\wordpad.exe", "InjectedPid": 1332, "InjectedTid": 1160}

In [9]: run(r'"c:\program files\windows nt\accessories\wordpad.exe"')
DRAKVUF injector v1.1-git20230901115228+3a0905b-1 Copyright (C) 2014-2023 Tamas K Lengyel
{"Plugin": "inject", "TimeStamp": "1707759074.275948", "Method": "CreateProc", "Status": "Success", "ProcessName": "c:\\program files\\windows nt\\accessories\\wordpad.exe", "Arguments": "", "InjectedPid": 1788, "InjectedTid": 2772}

In [10]: run(r"c:\program files\windows nt\accessories\wordpad.exe")
DRAKVUF injector v1.1-git20230901115228+3a0905b-1 Copyright (C) 2014-2023 Tamas K Lengyel
{"Plugin": "inject", "TimeStamp": "1707759075.768313", "Method": "CreateProc", "Status": "Success", "ProcessName": "c:\\program", "Arguments": "files\\windows nt\\accessories\\wordpad.exe", "InjectedPid": 988, "InjectedTid": 2348}
```

I see that quoting is missed almost everywhere, especially in https://github.com/CERT-Polska/drakvuf-sandbox/blob/master/drakrun/drakrun/lib/sample_startup.py. We should remove magic `%f` and use proper formatting. In addition, we should avoid using undocumented functions like `subprocess.list2cmdline` and use proper shlex alternative for Windows instead.
