### ISSUE TITLE
I am following this installation steps: https://drakvuf.com/ and I am getting error while running these commands: (1) make -j4 dist-tools (2) make -j debball

### ISSUE THREAD

**Issue by dhruvpatel56** [CERT-Polska/drakvuf-sandbox#726]
**What would you like to ask us?**

...

**Comment by dhruvpatel56** [comment]
Here's an error:

make[7]: *** [Makefile:19: build] Error 128
make[7]: Leaving directory '/home/.../drakvuf/xen/tools/firmware/ovmf-dir-remote'
make[6]: *** [/home/.../drakvuf/xen/tools/firmware/../../tools/Rules.mk:166: subdir-all-ovmf-dir] Error 2
make[6]: Leaving directory '/home/.../drakvuf/xen/tools/firmware'
make[5]: *** [/home/.../drakvuf/xen/tools/firmware/../../tools/Rules.mk:161: subdirs-all] Error 2
make[5]: Leaving directory '/home/.../drakvuf/xen/tools/firmware'
make[4]: *** [Makefile:44: all] Error 2
make[4]: Leaving directory '/home/.../drakvuf/xen/tools/firmware'
make[3]: *** [/home/.../drakvuf/xen/tools/../tools/Rules.mk:166: subdir-install-firmware] Error 2
make[3]: Leaving directory '/home/.../drakvuf/xen/tools'
make[2]: *** [/home/.../drakvuf/xen/tools/../tools/Rules.mk:161: subdirs-install] Error 2
make[2]: Leaving directory '/home/.../drakvuf/xen/tools'
make[1]: *** [Makefile:66: install] Error 2
make[1]: Leaving directory '/home/.../drakvuf/xen/tools'
make: *** [Makefile:140: install-tools] Error 2

**Comment by chivay** [comment]
This isn't the repo you're looking for.
Please file an issue in https://github.com/tklengyel/drakvuf repository.
