### ISSUE TITLE
how to use drakvuf-sandbox with kvm

### ISSUE THREAD

**Issue by mel2oo** [CERT-Polska/drakvuf-sandbox#731]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/41185794/188130326-cc053739-f4b9-4f9d-8f8d-746dba240823.png">

**Comment by BonusPlay** [comment]
Technically it works with KVM, but it's not recommended. The way you set it up is to run all the steps in a KVM-based VM. This means testing Xen inside KVM.
