### ISSUE TITLE
Insufficient apimon logs - Don't show everything in a process

### ISSUE THREAD

**Issue by lluisbessa** [CERT-Polska/drakvuf-sandbox#732]
Hello, I've set up drakvuf sandbox with drakvuf compiled from source (not the bundle because i wanted gnome gui).

By the way, i'm using ubuntu 20.04 as host, and guest  windows 7 64 bit professional.

![image](https://user-images.githubusercontent.com/106167946/191925506-d9847418-8335-4e84-a542-8953837d5ba9.png)

So here is my problem,
I'm analyzing a sample from the book Malware Analysis and Detection Engineering, it's sample-10-6 from 
https://github.com/poona/exercises-malware-analysis-and-detection-engineering

Supposedly it uses process hollowing, but after createprocessinternalw, I can't see NtCreateSection,NtMapViewOfSection,VirtualAllocEx, etc.

Any help would be appreciated.

I don't know for sure which do logs you need.

Thankyou

**Comment by BonusPlay** [comment]
Logs are created by `apimon` drakvuf plugin. You can add custom APIs to record. [here](https://github.com/tklengyel/drakvuf/blob/master/src/plugins/apimon/example/dll-hooks-list-win7x64) is the format, and it's being processed [here](https://github.com/CERT-Polska/drakvuf-sandbox/blob/master/drakrun/drakrun/main.py#L719-L727). So either add custom hooks to the karton task or modify default values in `/etc/drakrun/hooks.txt`

**Comment by lluisbessa** [comment]
Thank you, I have been testing and new logs are created. But even with the new apis, some times it shows createprocess and sometimes not, to be true, just one time showed me createprocess.

![image](https://user-images.githubusercontent.com/106167946/192459749-4e971de9-4d79-429f-af84-926f5f31c19f.png)

And with the same sample:

![image](https://user-images.githubusercontent.com/106167946/192459902-fbd03074-e5d9-4640-85d4-adebe2c80be0.png)

Thank you

**Comment by BonusPlay** [comment]
Interesting. Perhaps sample doesn't detonate in 2nd case?

**Comment by lluisbessa** [comment]
It's an interactive sample, so for sure it detonates, if you mean that it executes.

In the 2nd case and mores if it doesn't show findnextfilew, it doesn't log the createprocess api. Just worked one time. Any logs I can get info from these "errors" would help you?

Thanks

**Comment by BonusPlay** [comment]
Indeed, quite interesting. You can post analysis logs, maybe something interesting is in there.

**Comment by lluisbessa** [comment]
Here are the apimon logs.

Here are the apimon logs, if you need something else say me something.
[LogsApimon.zip](https://github.com/CERT-Polska/drakvuf-sandbox/files/9657241/LogsApimon.zip)

**Comment by lluisbessa** [comment]
I solve it, i had to rewrite these two last apis in hooks.txt, probably my bad, sorry for wasting your time.

ntdll.dll,NtCreateSection,log,phandle,access_mask,pobject_attributes,plarge_integer,ulong,ulong,handle
ntdll.dll,NtMapViewOfSection,log,handle,handle,pvoid,ulong,ulong,plarge_integer,pulong,section_inherit,ulong,ulong


Thank you
