### ISSUE TITLE
BUG: Plugin ipt startup failed

### ISSUE THREAD

**Issue by ananas4more** [CERT-Polska/drakvuf-sandbox#737]
# **Describe the bug**

## My environment

- Windows 11 Home
- VMWare Workstation Pro 16
- Ubuntu 18.04.6 LTS (as vmware machine, with 8 CPU cores and 8GB RAM)
- DRAKVUF Sandbox v0.18.2 installed followering [Getting started — DRAKVUF Sandbox v0.19.0-dev documentation](https://drakvuf-sandbox.readthedocs.io/en/latest/usage/getting_started.html)
- Guest VM is Windows 7 Ultimate with 4 vCPUs and 4GB RAM
- Tring to enable Intel Processor Trace followering [Using Intel Processor Trace Features (Experimental) — DRAKVUF Sandbox v0.19.0-dev documentation](https://drakvuf-sandbox.readthedocs.io/en/latest/ipt.html)

## Bugs

My DRAKVUF Sandbox work well without enabling IPT.  However, two bugs occur while trying to enable IPT:

- At the step of enabling IPT plugin in drakrun:  Xen would failed to startup guest vm Windows 7 after adding `vmtrace_buf_kb = 8192` follwring the tutorial.
- I replace the key `vmtrace_buf_kb` with `vmtrace_buf_size`, Xen then work well. DRAKVUF Sandbox also work well without enabling IPT plugin in web interface (After the installed IPT followering the tutorial).
- While enabling IPT plugin in web interface, [drakrun script](https://github.com/CERT-Polska/drakvuf-sandbox/blob/master/drakrun/drakrun/main.py) would catch an error when calling `drakvuf` subprocess in function `analyze_sample()`. `stderr` got `Failed to get trace buffer size\nPlugin IPT startup failed!`

# **How to reproduce**

## Bug 1: Invalid argument in Xen

Followering the tutorial:

> 1. In /etc/drakrun/config.ini, add ipt plugin under [drakvuf_plugins] section __all__ in order to enable IPT tracing.
> 2. **In /etc/drakrun/scripts/cfg.template add a new entry: vmtrace_buf_kb = 8192**
> 3. Execute systemctl restart drakrun@1 (repeat for each drakrun instance if you have scaled them up).

Without doing step 1 and 3 but step 2, DRAKVUF Sandbox will crash at starting up a guest VM via Xen. Drakrun log in the web interface would output: `Analysis attempt failed.`

Directly startup the guest VM Windows7 via Xen, it outputs an error message:

```
$ sudo xl create /etc/drakrun/configs/vm-1.cfg
Parsing config from /etc/drakrun/configs/vm-1.cfg
libxl: error: libxl_create.c:702:libxl__domain_make: domain creation fail: Invalid argument
libxl: error: libxl_create.c:1267:initiate_domain_create: cannot make domain: -3
``` 

Replace the key `vmtrace_buf_kb` with `vmtrace_buf_size`, Xen and Drakvuf Sandbox (without IPT enabled but installed) work well. 

## Bug 2: Failed to get trace buffer size in drakvuf

Modify `/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/main.py` to output stderr message of drakvuf subprocess:

At [drakrun/main.py](https://github.com/CERT-Polska/drakvuf-sandbox/blob/master/drakrun/drakrun/main.py) line 635~638:

```py
            try:
                res = subprocess.run(
                    drakvuf_cmd, capture_output=True, check=False, timeout=timeout + 60
                )
                self.log.info(f'Subprocess result: {res}')
``` 

Enabling IPT in the web interface of Drakvuf Sandbox.

Would got `Failed to get trace buffer size\nPlugin IPT startup failed!` in drakrun log.

**Comment by BonusPlay** [comment]
99.99% sure IPT won't work inside vmware. It requires direct CPU access.

**Comment by ananas4more** [comment]
> 99.99% sure IPT won't work inside vmware. It requires direct CPU access.

Thanks! I installed Drakvuf sandbox on my machine directly with Ubuntu 20.04, IPT plugin works well now. However, It seems that `codemon` and `sysmon` plugin NOT work correctly. Still followering the IPT usage tutorial:

> 1. Perform an analysis with IPT plugin enabled
> 2.Download the completed analysis from MinIO to your local hard drive
> 3. Find CR3 of the target process you want to disassemble (hint: syscall.log will contain CR3 values)
> 4. Execute drak-ipt-disasm --analysis . --cr3 <target_process_cr3> --vcpu 0

In step 3, I couldn't find syscall.log though I have enabled syscall plugin in the analysis. After step 4, drak-ipt-disasm raise FileNotFoundError: [Errno 2] No such file or directory: 'codemon.log'.

The followering are filenames I found in MinIO:

- drak-postprocess.log
- drakrun.log
- dump.pcap
- dumps.zip
- ipt.zip
- metadata.json

**Comment by ananas4more** [comment]
> > 99.99% sure IPT won't work inside vmware. It requires direct CPU access.
> 
> Thanks! I installed Drakvuf sandbox on my machine directly with Ubuntu 20.04, IPT plugin works well now. However, It seems that `codemon` and `sysmon` plugin NOT work correctly. Still followering the IPT usage tutorial:
> 
> > 1. Perform an analysis with IPT plugin enabled
> > 2. Download the completed analysis from MinIO to your local hard drive
> > 3. Find CR3 of the target process you want to disassemble (hint: syscall.log will contain CR3 values)
> > 4. Execute drak-ipt-disasm --analysis . --cr3 <target_process_cr3> --vcpu 0
> 
> In step 3, I couldn't find syscall.log though I have enabled syscall plugin in the analysis. After step 4, drak-ipt-disasm raise FileNotFoundError: [Errno 2] No such file or directory: 'codemon.log'.
> 
> The followering are filenames I found in MinIO:
> 
> * drak-postprocess.log
> * drakrun.log
> * dump.pcap
> * dumps.zip
> * ipt.zip
> * metadata.json

I have solved this problem! The stdout stream of `drakvuf` subprocess calling in `drakrun script` should't be captured by pipe. Do NOT modify `/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/main.py`, then it will generate log files of corresponding plugins correctly.

There are serveral troubles in the step executing `drak-ipt-disasm --analysis . --cr3 0x735bb000 --vcpu 0 --blocks` followering the tutorial. Some binay built in the step `Install required extra dependencies` aren't placed in the environment properly. One can find them in `$PROJECT_YOU_DOWNLOAD/bin`. Move them into `/usr/local/bin`, then the example would run well!
