### ISSUE TITLE
Test passed but cannot install under VMWare Workstation

### ISSUE THREAD

**Issue by lordtmk** [CERT-Polska/drakvuf-sandbox#758]
**Describe the bug**

When installing under Vmware (tried with Debian 10 and Ubuntu 20.04) it says that Xen installation doesn't pass the necessary tests.
Although it says everything is ok sometimes when i run draksetup test.

My CPU supports VT-x/EPT, VMWare virtualizes VT-x EPT :

![image](https://user-images.githubusercontent.com/42848077/213202559-85a0fa46-b7b2-439b-b5e2-54359037c678.png)

[2023-01-18 15:44:16,768][INFO] Checking xen-detect...
Running in PV context on Xen V4.16.
[2023-01-18 15:44:16,775][INFO] Testing if xl tool is sane...
[2023-01-18 15:44:16,788][INFO] Testing your Xen installation...
[2023-01-18 15:44:16,789][INFO] Checking if the test domain already exists...
[2023-01-18 15:44:16,796][INFO] Creating new test domain...
[2023-01-18 15:44:16,796][INFO] Creating VM test-hvm64-example
[2023-01-18 15:44:16,866][INFO] Testing altp2m feature...
Succesfully enabled SLAT
[2023-01-18 15:44:16,874][INFO] Performing simple XTF test...
[2023-01-18 15:44:16,877][INFO] Unpausing VM test-hvm64-example
[2023-01-18 15:44:21,906][ERROR] Preflight check with Xen Test Framework doesn't pass. Your hardware might not support VT-x. Logs:

[2023-01-18 15:44:21,907][ERROR] Your Xen installation doesn't pass the necessary tests.
[2023-01-18 15:44:21,907][ERROR] Sanity check failed.

**How to reproduce**

1. Install drakcore and drakrun
2. Execute `draksetup test`

**Comment by BonusPlay** [comment]
Thanks for creating issue, will try to recreate on my end.

**Comment by lordtmk** [comment]
Hi, thanks for quick reply : 

Architecture :                          x86_64
Mode(s) opératoire(s) des processeurs : 32-bit, 64-bit
Boutisme :                              Little Endian
Tailles des adresses:                   45 bits physical, 48 bits virtual
Processeur(s) :                         1
Liste de processeur(s) en ligne :       0
Thread(s) par cœur :                    1
Cœur(s) par socket :                    1
Socket(s) :                             1
Nœud(s) NUMA :                          1
Identifiant constructeur :              GenuineIntel
Famille de processeur :                 6
Modèle :                                151
Nom de modèle :                         12th Gen Intel(R) Core(TM) i3-12100F
Révision :                              5
Vitesse du processeur en MHz :          3302.010
BogoMIPS :                              6604.93
Constructeur d'hyperviseur :            Xen
Type de virtualisation :                complet
Cache L1d :                             48K
Cache L1i :                             32K
Cache L2 :                              1280K
Cache L3 :                              12288K
Nœud NUMA 0 de processeur(s) :          0
Drapaux :                               fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase bmi1 avx2 bmi2 erms rdseed adx clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 gfni vaes vpclmulqdq rdpid md_clear arch_capabilities

**Comment by BonusPlay** [comment]
Could you post entire output of `lscpu`? I'm not seeing `vmx` and `ept` in your capabilities list.

**Comment by lordtmk** [comment]
This is the entire output, i can't ask more

**Comment by BonusPlay** [comment]
Cannot reproduce on my end. Based on lscpu output seem to be missing features on your CPU. Are you sure you selected proper settings in vmware? Refer to https://github.com/tklengyel/drakvuf/issues/1600#issuecomment-1385447356

**Comment by lordtmk** [comment]
Yep, everything is OK, will try with a different proc then. Leaving this opened maybe i can install it this weekend.
