### ISSUE TITLE
Missing comma on snapshot_import in draksetup.py

### ISSUE THREAD

**Issue by fabionitto** [CERT-Polska/drakvuf-sandbox#759]
```
            try:
                subprocess.run(["xl" "create", cfg_path], check=True)
            except subprocess.CalledProcessError:
                logging.exception("Failed to launch VM vm-0")
                return
```

subprocess.run call is missing a comma on ``"xl", "create"`` at line 1215. Or the double quotes should be supressed: ``"xl create"``

**Comment by BonusPlay** [comment]
That is indeed correct. I wonder why none of the tools found this :thinking: 

Expect 0.19 coming soon-ish.
