### ISSUE TITLE
Installation queries

### ISSUE THREAD

**Issue by Dylan818** [CERT-Polska/drakvuf-sandbox#773]
**What would you like to ask us?**
Hi, I'm reading the installation guide at https://drakvuf-sandbox.readthedocs.io/en/latest/usage/getting_started.html .

I have some questions regarding the installation steps namely:

Step 2:
apt update
apt install ./xen-hypervisor*.deb
apt install ./drakvuf-bundle*.deb
reboot

what does the ./xen-hypervisor*.deb and drakvuf-bundle*.deb refer to? I have installed the latest packages from the github page.

The other steps also follow a similar naming convention for the files needed to be installed. 

I am trying to install DRAKVUF on Ubuntu 22.04.06 Focal, with an Intel Core i7-7700. Thank you and I apologize if this is lengthy, I am quite new to this so please be patient with me.

...

**Comment by krzysdz** [comment]
`xen-hypervisor` and `drakvuf-bundle` are built from [drakvuf](https://github.com/tklengyel/drakvuf) and are responsible for virtualization and analysis/tracing. These packages are [built by the CI](https://ci.drakvuf.cert.pl/CERT-Polska/drakvuf-sandbox/49/6/2), but it looks like the artifacts are not published anywhere. Before #755 was merged, `drakvuf-bundle` contained both Xen and DRAKVUF in a single package, so if you are using the version from release [v0.18.2](https://github.com/CERT-Polska/drakvuf-sandbox/releases/tag/v0.18.2), just install `drakvuf-bundle`, `drakcore` and `drakrun`.

These are the packages required for Ubuntu **20.04** (Focal Fossa):
![drakvuf-bundle, drakcore and drakrun installation packages for focal](https://user-images.githubusercontent.com/12915102/228390315-5eec7ecb-d0fb-4211-b0c5-6a01d1c11d6e.png)

If you want to use the latest version and don't want to build it yourself, you can try using the builds from [tklengyel/drakvuf](https://github.com/tklengyel/drakvuf/releases/tag/1.0) or GitHub CI [build](https://github.com/CERT-Polska/drakvuf-sandbox/actions/runs/4537487844) from #772 (the `drakvuf-bundle-debs` zip contains both Xen and DRAKVUF `.deb`s).

**Comment by Dylan818** [comment]
Ah okay, thank you. I am running into this issue when building the installation packages. After running "sudo ./drakrun/package/build.sh", I get an error pertaining to the unsuccessful installation of yara python. How do I solve it?

[error.txt](https://github.com/CERT-Polska/drakvuf-sandbox/files/11107747/error.txt)

**Comment by psrok1** [comment]
Latest release of yara-python broke few things, it's not fixed yet.

The possible cause is missing libssl-dev, so you should try to install this additional dependency using apt. If it doesn't work, another thing you can try is to add version pin `yara-python==4.2.3` into `/drakrun/requirements.txt` file

**Comment by krzysdz** [comment]
As @psrok1 wrote, adding `libssl-dev` to line 8 or 9 in [`drakvuf-sandbox/drakrun/package/Dockerfile`](https://github.com/CERT-Polska/drakvuf-sandbox/blob/ba673d6d86869204e5695a9890e702a1ac30a351/drakrun/package/Dockerfile#L6-L13) fixes the build.

https://github.com/CERT-Polska/drakvuf-sandbox/blob/ba673d6d86869204e5695a9890e702a1ac30a351/drakrun/package/Dockerfile#L6-L13

Also, if you're using Ubuntu 20.04 (Focal Fossa), I'd suggest building the packages with `BASEIMAGE=ubuntu:20.04`, because by default the images are built using a Debian Buster image and use Python 3.7, while Ubuntu 20.04 uses Python 3.8.
