### ISSUE TITLE
Multiple Guest VM Setup

### ISSUE THREAD

**Issue by Sukhj1nder** [CERT-Polska/drakvuf-sandbox#793]
Hi Tamas K. Lengyel @tklengyel,

I am an honors student working on a project regarding malware analysis.

The project utilizes the DRAKVUF Sandbox and expands its Web UI to make it more friendly for people with less technical experience.

I have a question regarding the setup of the guest vms for the malware analysis, I am not able to find any resources covering how to add more Guest VMs using the provided packages (draksetup and drakrun) within the same install of drakvuf-sandbox.

I have found that the VMs configuration is saved in a json file, but I am unsure how to add an additional guest vm with the provided libraries.

When I use the ‘draksetup install’ command it destroys the vm that I had setup and overwrites it with the new one.

Any help with this would be greatly appreciated.

Kind Regards,

Sukhjinder Singh

**Comment by BonusPlay** [comment]
1) This project is not maintained by Tamas.
2) This feature is currently not supported, refer to #462.
