### ISSUE TITLE
Xen-hypervisor is not in releases

### ISSUE THREAD

**Issue by ArikRahman** [CERT-Polska/drakvuf-sandbox#811]
**What would you like to ask us?**
I am not sure as to which xen hypervisor to get, as it is not in the releases on github.
...
![image](https://github.com/CERT-Polska/drakvuf-sandbox/assets/40479733/37e59cf8-a8b6-444e-be4e-0bbc6ffa3f15)

**Comment by abbasimuha** [comment]
You do not need to install xen hypervisor with the latest release. Please check the following comment:
https://github.com/CERT-Polska/drakvuf-sandbox/issues/773#issuecomment-1487746870
