### ISSUE TITLE
install drakcore error ubuntu22.04

### ISSUE THREAD

**Issue by cctv130** [CERT-Polska/drakvuf-sandbox#820]
![1695038375043](https://github.com/CERT-Polska/drakvuf-sandbox/assets/133784576/038d1eaa-96ba-4749-b864-9b10b8a11139)

**Comment by BonusPlay** [comment]
Seems like redis is down. Did you install and start it before installing DRAKVUF-Sandbox?

**Comment by cctv130** [comment]
@BonusPlay Yes, all basic projects have been installed.

**Comment by cctv130** [comment]
@BonusPlay I used 20.04 to install successfully，It seems that the project still has many problems.

**Comment by BonusPlay** [comment]
22.04 isn't supported yet. But worth keeping open for later.

**Comment by cctv130** [comment]
@BonusPlay Another problem was found, after executing the command 'draksetup test', the error qemu could not find libnettle.so.6 in ubuntu server 20.04

**Comment by psrok1** [comment]
22.04 is not supported yet and I think we should track further problems in this issue: https://github.com/CERT-Polska/drakvuf-sandbox/issues/820
