### ISSUE TITLE
Where is Xen-Hypervisor Release download

### ISSUE THREAD

**Issue by TacitTactics** [CERT-Polska/drakvuf-sandbox#877]
**What would you like to ask us?**
The doc says the following: "Always install xen-hypervisor from drakvuf-sandbox release. Mismatching packages from different releases may lead to unexpected results." Where can I find it? 
...

**Comment by Plasgianp** [comment]
I think we need to install it from the official Drakvuf release.

**Comment by psrok1** [comment]
I think there's leftover in the docs from rollbacked Drakvuf upgrade. Currently released Drakvuf Sandbox version is based on Drakvuf 0.8 with backports (https://github.com/CERT-Polska/drakvuf/tree/v0.8-backports) and this version includes Xen in the drakvuf-bundle.deb.

In future version, Xen will be in a separate package that will be also included in the release files.
