### ISSUE TITLE
Error Occuring while Analyzing Malware samples in Drakvuf Sandbox : "ERROR_VIRUS_INFECTED , ERROR_ELEVATION_REQUIRED"

### ISSUE THREAD

**Issue by TechDopamine** [CERT-Polska/drakvuf-sandbox#897]
While analyzing a malicious sample in Drakvuf Sandbox this kind of error were shown as output in Analysis Log.(These are the output two different malicious exe.)

ERROR 1 :-
{"Plugin": "inject", "TimeStamp": "1716813347.044521", "Method": "CreateProc", "Status": "Error", "ErrorCode": 225, "Error": "ERROR_VIRUS_INFECTED"}

ERROR 2 :-
{"Plugin": "inject", "TimeStamp": "1716810114.595875", "Method": "CreateProc", "Status": "Error", "ErrorCode": 740, "Error": "ERROR_ELEVATION_REQUIRED"}

How to solve these error....?

**Comment by psrok1** [comment]
Hi! Drakvuf doesn't do any antivirus evasion or unattended process elevation, so you need to prepare your VM yourself to avoid that. Disable UAC (`Never notify` option) and Windows Defender on your snapshot to execute malware properly. If you want to analyze Office files, remember also to enable macro execution without confirmation.

See also:
- https://drakvuf-sandbox.readthedocs.io/en/latest/usage/optional_features.html#ms-office-file-support
- https://drakvuf-sandbox.readthedocs.io/en/latest/usage/managing_snapshots.html#snapshot-modification
