### ISSUE TITLE
Compatibility study for Azure Cloud

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/drakvuf-sandbox#92]
Related bug: #90

The default `azure` kernel shipped with Azure Cloud Ubuntu 18.04 doesn't declare Xen support, thus the grub hook doesn't see it as a suitable Dom0 system.

Some guide on how to prepare a custom Ubuntu VM with a generic kernel:
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-ubuntu

Another options is to simply try to replace `azure` kernel with a stock one, but the Xen Dom0 doesn't work out of the box in such setup:
https://ubuntu.com/blog/microsoft-and-canonical-increase-velocity-with-azure-tailored-kernel

**Comment by chivay** [comment]
It's worth noting that not all instance types support nested virtualization.
Consult the table linked below.
https://docs.microsoft.com/en-us/azure/virtual-machines/acu

**Comment by chivay** [comment]
Seems like we would experience the same issue as with GCP:
https://github.com/CERT-Polska/drakvuf-sandbox/issues/93#issuecomment-625328555

Closing for now, with hope that some day nested virtualization will be mature enough for this to work.
