### ISSUE TITLE
Compatibility study for Google Cloud Platform

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/drakvuf-sandbox#93]
Check whether drakvuf-sandbox is feasible on GCP on at least one of the supported systems. Info needed: whether some custom hacks/adjustments are needed and if we could document them/implement some improvements dedicated for GCP.

**Comment by icedevml** [comment]
Info from @chivay: GCP on 5.6 generic kernel ( https://kernel.ubuntu.com/~kernel-ppa/mainline/?C=N;O=D ) with Windows 10 guest seems to work OK.

**Comment by chivay** [comment]
By following this tutorial I've managed to the the Windows VM up and running:
https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances

Used instance image: Debian 10 with custom kernel package (`CONFIG_XEN_DOM0=y` is  required)
Used Windows ISO: Windows 10 1909 (MD5: `d1f08aea37586702f6fbe2fe3ea8c3fd` )

**Comment by icedevml** [comment]
> The process failed during draksetup postinstall while running vmi-win-offsets step. It timed out after 30s.

I've reproduced this behavior outside GCP, this is just the issue of LibVMI not detecting something in the kernel. We need to further debug what exactly.

**Comment by icedevml** [comment]
For sure there must be some problem with how `vmi-win-offsets` works. I've found KPGD manually and I'm able to run `drakvuf` against this Windows 10 using:

```
drakvuf -d vm-0 -k 0x1aa002 -r /var/lib/drakrun/profiles/kernel.json
```

`vmi-win-offsets` also succeeds to do so, but this is not always the case. When it doesn't succeed, it enters some crazy loop of scanning the whole physical memory. I bet "fail fast" approach would be better for our case.

**Comment by icedevml** [comment]
After commenting paths leading to full memory scan in LibVMI mode, the success rate of `vmi-win-offsets` increases significantly. Also with such modification it's possible to retry in case it doesn't succeed to find kernel for the first time.

We need to study how `vmi-win-offsets` works and what are the options to improve it. For a quick solutions:

* terminating `vmi-win-offsets` (as we do now) simply leaves the VM paused, because there is no corresponding `xc_domain_unpause` call, so the pause counter is left >0, maybe we should just implement a graceful signal handler that would unpause the VM prior to user-induced-terminating the program?
* some `--fail-fast` switch for `vmi-win-offsets` would be also very handy
* long topic - study the exact causes

```diff
diff --git a/libvmi/os/windows/core.c b/libvmi/os/windows/core.c
index 62ab1bd..654385d 100644
--- a/libvmi/os/windows/core.c
+++ b/libvmi/os/windows/core.c
@@ -842,8 +842,8 @@ init_from_json_profile_real(vmi_instance_t vmi, reg_t kpcr_register_to_use)

         if ( VMI_SUCCESS == kpcr_find1(vmi, windows, kpcr_reg) ) {}
         else if ( VMI_SUCCESS == kpcr_find2(vmi, windows) ) {}
-        else if ( VMI_SUCCESS == kpcr_find3(vmi, windows) ) {}
-        else if ( VMI_SUCCESS == kpcr_find4(vmi, windows, kpcr_reg) ) {}
+        //else if ( VMI_SUCCESS == kpcr_find3(vmi, windows) ) {}
+        //else if ( VMI_SUCCESS == kpcr_find4(vmi, windows, kpcr_reg) ) {}
         else goto done;

         if ( VMI_FAILURE == vmi_translate_kv2p(vmi, windows->ntoskrnl_va, &windows->ntoskrnl) || !windows->ntoskrnl ) {
diff --git a/libvmi/os/windows/kdbg.c b/libvmi/os/windows/kdbg.c
index e0d9a8f..12ed03b 100644
--- a/libvmi/os/windows/kdbg.c
+++ b/libvmi/os/windows/kdbg.c
@@ -693,6 +693,8 @@ status_t find_kdbg_address(

     dbprint(VMI_DEBUG_MISC, "**Trying find_kdbg_address\n");

+    return VMI_FAILURE;
+
     status_t ret = VMI_FAILURE;
     *kdbg_pa = 0;
     addr_t paddr = 0;
@@ -1194,6 +1196,7 @@ init_from_kdbg(
     // so lets try our kdbg search method
 find_kdbg:
     dbprint(VMI_DEBUG_MISC, "**Attempting KdDebuggerDataBlock search methods\n");
+    goto exit;

     if (VMI_SUCCESS == find_kdbg_address_instant(vmi, &kdbg_pa, &kernbase_pa, &kernbase_va)) {
         goto found;
```

**Comment by chivay** [comment]
After long and tedious debugging session, it seems that GCP won't be able to run drakvuf. LibVMI errors with:
```
VMI_ERROR: xen_start_single_step error: no system support for event type
Failed to register singlestep for vCPU 0
VMI_ERROR: xc_altp2m_switch_to_view returned rc: -1
```
Attaching full debug log
[log.txt](https://github.com/CERT-Polska/drakvuf-sandbox/files/4593939/log.txt)
