### ISSUE TITLE
xc: error: panic: xc_dom_boot.c:122: xc_dom_boot_mem_init: can't allocate low memory for domain: Out of memory

### ISSUE THREAD

**Issue by unexpectedBy** [CERT-Polska/drakvuf-sandbox#97]
**Describe the bug**

**when im try this command: sudo draksetup install --iso /opt/path_to_windows.iso**

**logs:**

root@ubuntu:/home/fmt# draksetup install --iso win7.iso
[2020-05-09 05:50:33,413][INFO] Ensuring that drakrun@* services are stopped...
[2020-05-09 05:50:35,586][INFO] Performing installation...
[2020-05-09 05:50:35,766][INFO] Checking xen-detect...
Running in PV context on Xen V4.13.
[2020-05-09 05:50:35,921][INFO] Testing if xl tool is sane...
[2020-05-09 05:50:38,503][INFO] Generated VM configuration for vm-0
Parsing config from /etc/drakrun/configs/vm-0.cfg
xc: error: panic: xc_dom_boot.c:122: xc_dom_boot_mem_init: can't allocate low memory for domain: Out of memory
libxl: error: libxl_dom.c:762:libxl__build_dom: xc_dom_boot_mem_init failed: Cannot allocate memory
libxl: error: libxl_create.c:1420:domcreate_rebuild_done: Domain 1:cannot (re-)build domain: -3
libxl: error: libxl_domain.c:1177:libxl__destroy_domid: Domain 1:Non-existant domain
libxl: error: libxl_domain.c:1131:domain_destroy_callback: Domain 1:Unable to destroy guest
libxl: error: libxl_domain.c:1058:domain_destroy_cb: Domain 1:Destruction of domain failed
[2020-05-09 05:50:48,029][ERROR] Failed to launch VM vm-0
Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.6/site-packages/drakrun/draksetup.py", line 201, in install
    subprocess.run('xl create {}'.format(shlex.quote(cfg_path)), shell=True, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'xl create /etc/drakrun/configs/vm-0.cfg' returned non-zero exit status 3.

**my vm-0.cfg info:**

root@ubuntu:/home/fmt# cat /etc/drakrun/configs/vm-0.cfg
arch = 'x86_64'
name = "vm-0"
maxmem = 2048
memory = 2048
vcpus = 2
maxcpus = 2
builder = "hvm"
boot = "cd"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "restart"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0"
vncdisplay=0
vncpasswd="lAHA0VnXQv0ElbHfugK0"
usb = 1
usbdevice = "tablet"
altp2m = 2
shadow_memory = 16
audio=1
soundhw='hda'
vif = [ 'type=ioemu,model=e1000,bridge=drak0' ]
disk = [ "tap:qcow2:/var/lib/drakrun//volumes/vm-0.img,xvda,w", "file:/home/fmt/win7.iso,hdc:cdrom,r" ]

![error](https://user-images.githubusercontent.com/6081236/81474408-a62c2e00-91db-11ea-9770-95f5fdfa88df.png)

**Comment by BonusPlay** [comment]
Hello, could you please provide output of
```
xl info
```
command? It would help narrowing down the bug.

**Comment by BonusPlay** [comment]
Not a bug, please consult [this section of readme](https://github.com/CERT-Polska/drakvuf-sandbox#debug-cant-allocate-low-memory-for-domain).

**Comment by unexpectedBy** [comment]
thansk bro! works fine!
![image](https://user-images.githubusercontent.com/6081236/81475205-1ee1b900-91e1-11ea-9a07-26bc0f69fa2d.png)
