### ISSUE TITLE
Don't find drakvuf_sandbox*.whl

### ISSUE THREAD

**Issue by frenchy35** [CERT-Polska/drakvuf-sandbox#982]
All is in the tittle, I don't find le file (drakvuf_sandbox*.whl), witch is use in the point 4 of the installation procedure (https://drakvuf-sandbox.readthedocs.io/en/latest/usage/getting_started.html) Please sry for my English, I'm French

Great thanks in advance

Best regards

__ 
Philipp

...

**Comment by psrok1** [comment]
Hi!

Documentation is generated from current master, so things may be a bit undocumented.

All installation files can be found in Assets: https://github.com/CERT-Polska/drakvuf-sandbox/releases/tag/v0.19.0-alpha1
If you want to have "bleeding edge" version, you can build the project from sources or use files from CI artifacts: https://github.com/CERT-Polska/drakvuf-sandbox/actions/runs/11216202034 (the most bottom panel on this page).

Current stable version (v0.18.2) is based on .deb files. Installation instructions for v0.18.x can be found here: https://drakvuf-sandbox.readthedocs.io/en/v0.18.1/usage/getting_started.html#basic-installation

**Comment by frenchy35** [comment]
Great thanks I’ll continue testing 

best regard 

__ 
Philipp

**Comment by ohault** [comment]
May I suggest to update on https://github.com/CERT-Polska/drakvuf-sandbox/releases/tag/v0.18.2 

The hyperlink [Getting started section in documentation](https://drakvuf-sandbox.readthedocs.io/en/latest/usage/getting_started.html) could be updated to point towards the following URL : 

https://drakvuf-sandbox.readthedocs.io/en/v0.18.1/usage/getting_started.html#basic-installation
